- types/applications/forms/item.d.ts
- types/framework/entities/item.d.ts
This slightly improves the types of the `actor` properties in `Item` and  `ItemSheet`. In particular, this also solves the issue with the actor property of `Item` circularly referencing itself somehow. The underlying issue was that the property was typed as `Actor` earlier, which was being mistaken as the namespace `Actor`. Fixes #217.
> Improve typing of actor properties in Item and ItemSheet

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/wrong_type.md
- .github/workflows/checks.yml
This removes kmoschcau as the default assignee from the issue templates
and replaces the broken type check action with just a plain tsc run.
> Remove issue assignee and replace type check action

- types/framework/entities/actor.d.ts
- types/framework/entities/item.d.ts
- types/framework/entity.d.ts
This also adjusts the return type of `Actor.prepareData` and `Item.prepareData` to `void`.
Fixes #244
> Fix Entity.prepareData

- .eslintrc.js
- test-d/utils.test-d.ts
- tsconfig.eslint.json
- tsconfig.json
- types/typesUtils.d.ts
- types/utils.d.ts
This fixes the type definition of `duplicate`.
For convenience, you can provide `lenient` as generic parameter so that it does not convert `number` to `number | null`, which it does by default because `duplicate` turns `NaN`, `Infinity`, and `-Infinity` into `null`. So in theory, using `number | null` is actually the correct thing. However, often one knows that the fields contain actual numbers. Unfortunately, the type system cannot represent this, so in order to improve usability, this option to be lenient in this regard is available.
This introduces quite a lot of internal utility types. It might make sense to put them in other locations or in namespaces. Please feel free to give feedback regarding this topic.
This also adds the `test-d` directory to the `incldue` of `tsconfig.json` …
> Fix type definition of duplicate

- test-d/framework/entities/activeEffect.test-d.ts
- types/framework/entities/activeEffect.d.ts
- types/framework/entities/actor.d.ts
- types/framework/entities/embeddedEntity.d.ts
- types/framework/entities/item.d.ts
This slightly improved the type definitions of `ActiveEffect`, mainly by making it generic in the parent.
Fixes #241
> Improve type definitions of ActiveEffect

- test-d/framework/entities/chatMessage.test-d.ts
- types/framework/entities/chatMessage.d.ts
The create method was overloaded from the base entity version is such a
way that it was valid to pass full entities on the data object. This
commit adds interfaces and changes the call signature to reflect that
difference.
> Fixup for ChatMessage

- types/game.d.ts
This simply makes `Game` extends `Record<string, unknown>`, effectively making it possible to add properties to any instance of `Game` (such as `game`):
```ts
game.myCustomProp = 'some string';
```
Unfortunately this is not very helpful for retrieval of custom properties from a `Game` as it will always be typed as `unknown` but it at least covers the common use case of adding stuff to `game` in order to make it available to be used in macros. If we find a better solution that also covers retrieval, we can switch to that solution.
fixes #239
> Make it possible to dynamically add properties to a Game

- types/applications/dialog.d.ts
- Make the `options` parameter in `Dialog`'s constructor optional
- Make `icon` and `label` optional in `Dialog.Button`. The JSDoc documents that differently but in the end, these string are just passed to handlebars which simply doesn't render them if you omit them.
Fixes #266
Fixes #267
> Small Dialog Fixes

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/wrong_type.md
This change has already been done in foundry-0.7.9 but it's not effective because GitHub looks at the templates in the master branch (as it is the default branch)
> Remove default assignee from issue templates

- test-d/types/core/rolls/diceTerms/coin.test-d.ts
- test-d/types/core/rolls/diceTerms/die.test-d.ts
- test-d/types/core/rolls/diceTerms/fateDie.test-d.ts
- types/core/rolls/diceTerms/coin.d.ts
- types/core/rolls/diceTerms/diceTerm.d.ts
- types/core/rolls/diceTerms/die.d.ts
I tried to make it work to have the `MODIFIERS` of the subclasses accept functions that take their concrete type (e.g. `Die`) as this parameter instead of the generic `DiceTerm`. However, Typescript complained that the subclass is not properly extending `DiceTerm` then. I guess this should be good enough for most uses cases anyways.
> Make MODIFIERS extendable for all dice terms

- test-d/types/applications/forms/actorSheet.test-d.ts
- test-d/types/applications/forms/itemSheet.test-d.ts
- types/applications/baseEntitySheet.d.ts
- types/applications/formApplication.d.ts
- types/applications/forms/actorSheet.d.ts
- types/applications/forms/itemSheet.d.ts
- types/core/settings/clientSettings.d.ts
- types/framework/entity.d.ts
Makes FormApplication generic on the return type of getData. Updates
BaseEntitySheet to match these changes. Makes the O parameter default to
inferred from D in the case that it extends the default return type, or
{} if not.
> Update FormApplication to be less opinionated about getData return type.

- types/applications/application.d.ts
- types/ui/tabs.d.ts
I'm still a bit unsure with how to handle the default parameter of the constructor. I simply did not add it because it doesn't make any sense as it sets `navSelector` to undefined. This makes the resulting `Tabs` instance basically unusable. Please leave feedback regarding that.
Fixes #49
> Update Tabs to 0.7.9

- test-d/types/framework/entity.test-d.ts
- types/framework/entity.d.ts
- types/typesUtils.d.ts
This PR improves `Entity.create` in 2 ways:
- The return type is now correct also when an array of length 1 is passed
- When calling `create` on a class that is extending `Entity`, the return type correctly uses that subclass instead of `Entity` automatically, i.e. it is no longer necessary to explicitly provide the resulting class as type parameter or cast.
> Improve Entity.create

- test-d/types/framework/entity.test-d.ts
- types/framework/entities/actor.d.ts
- types/framework/entities/chatMessage.d.ts
- types/framework/entities/item.d.ts
- types/framework/entities/scene.d.ts
- types/framework/entity.d.ts
- types/typesUtils.d.ts
This PR improves the type definitions of `Entity.create`, `Entity.update`m and `Entity.delete` in the following ways:
- Correctly infer the return type if an array with one element is passed.
- Automatically infer the entity type based on the concrete class the method is called on (i.e. there is no more need to explicitly specify the concrete entity class as type parameter).
There are also some other small improvements to `Entity`
> Improve typing of Entity

- index.d.ts
- types/actorTokenHelpers.d.ts
This adds the `ActorTokenHelpers` class. It's not yet ideal because it suffers from the same problem as other methods related to embedded entities. But it's something that can be built upon once we find a general solution to this problem. And it's a t least somewhat usable.
Fixes #123 (at least somewhat)
> Add ActorTokenHelpers

- index.d.ts
- types/game.d.ts
- types/pixi/canvas.d.ts
- types/pixi/tokenLayer.d.ts
Adds the bare minimum types for `canvas.tokens` on the global scope so.
Also removes the `{ ready: boolean }` type from the global `canvas`. Canvas is either a Canvas (which already has ready: boolean) or it is null upon initial declaration. Leave it up to the system/module developer to evaluate ready or not.
> Add tokens to canvas global

- foundry/roll.d.ts
Previously, this would have defined `rollMode` to be of type `'PUBLIC' | 'PRIVATE' | 'BLIND' | 'SELF' | null`, which is incorrect. We need the values instead of the keys.
> Roll fixup

- foundry/application.d.ts
- foundry/applications/filePicker.d.ts
- foundry/applications/formApplications/baseEntitySheet.d.ts
- foundry/applications/sidebarTabs/chatLog.d.ts
- foundry/applications/sidebarTabs/sidebarDirectories/playlistDirectory.d.ts
- foundry/config.d.ts
- foundry/constants.d.ts
- foundry/entities/playlist.d.ts
- foundry/entities/scene.d.ts
- foundry/game.d.ts
- foundry/pointSource.d.ts
- foundry/roll.d.ts
- foundry/socketInterface.d.ts
- types/utils.d.ts
Foundy doesn't define the enums and unfortunately, they are not automatically replaced at compile time. This means that people could try to use the enums which would result in runtime errors. For this reason, this PR removes all the enums and replaces them with types if applicable.
> Remove enums

- foundry/applications/formApplications/baseEntitySheets/journalSheet.d.ts
Hey guys, I would like to help you with types for 0.7.9. I'm not sure if there are any guidelines you want me to follow, so feel free to comment my first attempt on JournalSheet types. I've tried to use `ActorSheet` as main example of how it should look.
I'm not really sure if providing the `SheetMode` enum is good idea - according to foundry code there are only two values, but comments in source code treat those as `{string}`. Let me know what is your opinion in that case.
EDIT: I can see another PR in which you've just removed all enums, so I guess I should remove that SheetMode as well.
> Update JournalSheet to 0.7.9

- README.md
Add `"moduleResolution": "node"` requirement to the readme.
> add moduleResolution: node to readme

- foundry/application.d.ts
- foundry/applications/formApplication.d.ts
- foundry/applications/formApplications/imagePopout.d.ts
Closes #59 
I changed `O` generic in `FormApplication` to allow primitives as constructor parameter (as suggested by BoltsJ in #59).
Please, let me know if the way I handled the first generic (`D`) is a proper way of doing that. As far as I can see, the `D` generic of `FormApplication` is mostly used for returning type of `getData` method, so I've created `ImagePopout.Data` type with additional fields (pulled out from `ImagePopout.getData` source code). 
Maybe I should make `D` a little bit more strict for `ImagePopoutData` and change it to `D extends ImagePopout.Data = ImagePopout.Data`?
Also note that, according to source code, `_updateObject` is not overridden in `ImagePopout`. Unfortunately, `FormApplication._updateObject` is abstract, so it forces us to `implement it` in some way. In …
> [ImagePopout] Update types to 0.7.9

- foundry/applications/formApplications/baseEntitySheet.d.ts
- foundry/applications/formApplications/baseEntitySheets/journalSheet.d.ts
- foundry/applications/formApplications/imagePopout.d.ts
I made a few adjustments:
1. `options` parameter should be Partial, but it wasn't.
2. Added defaultValues for JournalSheet.Options.
3. Narrow down returning type of getData (it is never a promise)
One thing I noticed - I've made default value of `viewPermission` in the same way as it is done in BaseEntitySheet, but in BaseEntitySheet there is a typo (`Const.EntityPermissions`). Also, it references `type EntityPermission = ValueOf<typeof ENTITY_PERMISSIONS>;`, which is computed to `0 | 1 | 2 | 3`, so `.None` references nothing. 
Maybe I should stick to `ENTITY_PERMISSIONS.NONE` as default value instead, and also change the `BaseEntitySheet.Options.viewPermission` to `ENTITY_PERMISSIONS.LIMITED`. What do you think?
> [JournalSheet] Adjust JournalSheet types definitions

- .github/workflows/checks.yml
- .github/workflows/release.yml
This adds a workflow that publishes to npm when a release is created. The basic workflow to publish a new version then becomes this:
- Locally, run
```
npm version prerelease
```
This increases the prerelease version number (i.e. the number behind the "-") and creates a tag for the new version.
- Push the created tag and the branch:
```
git push --follow-tags
```
If you don't have admin priviledges, you need to create a PR instead.
- Create a new release for the tag in GitHub. This triggers the workflow and automatically publishes the version to npm.
> Add publish workflow

- foundry/applications/formApplication.d.ts
I noticed a few discrepancies with the types for the FormApplication Editor.
- There was a property missing from the [FormApplication Editor Interface](https://github.com/League-of-Foundry-Developers/foundry-vtt-types/blob/foundry-0.7.9/foundry/applications/formApplication.d.ts#L214). There is an active property missing, can see it being [set in the foundry.js](https://foundryvtt.com/api/foundry.js.html#line5368) (line 5368)
- The mce property from the [FormApplication Editor Interface](https://github.com/League-of-Foundry-Developers/foundry-vtt-types/blob/foundry-0.7.9/foundry/applications/formApplication.d.ts#L214) can be null in addition to the tinyMCE editor type. Referencing the [foundry.js again](https://foundryvtt.com/api/foundry.js.html#line5368) (line 5367)
- The bigger change is …
> FormApplication Editor Changes - Foundry 0.7.9

- foundry/applications/invitationLinks.d.ts
- index.d.ts
Added the class for Invitation links based on the code in the [foundry.js](https://foundryvtt.com/api/foundry.js.html#line24676)
Placed under the applications folder as it extends the base application class.
For issue #102
> InvitationLinks - Foundry 0.7.9

- foundry/applications/sceneNavigation.d.ts
Updated the Scene Navigation class to work with foundry 0.7.9 as found in the [foundry.js](https://foundryvtt.com/api/foundry.js.html#line20703)
Resolves #77
> Scene Navigation - Foundry 0.7.9

- foundry/cameraPopoutAppWrapper.ts
- index.d.ts
Added the class for the CameraPopoutAppWrapper from the 0.7.9 [foundry.js](https://foundryvtt.com/api/foundry.js.html#line21425).
Oddity is this class looks like it should extended the Application class but it does not.
resolves issue #81
> CameraPopoutAppWrapper - Foundry 0.7.9

- foundry/entities/user.d.ts
- foundry/roll.d.ts
See https://gitlab.com/foundrynet/foundryvtt/-/issues/4758 and https://gitlab.com/foundrynet/foundryvtt/-/issues/4759
> Fix Roll.render and roll.getTooltip return types

- foundry/config.d.ts
As discussed on discord in the tools-and-workflow channel, to allow modules to define system specific overrides to CONFIG via declaration merging. After doing this change, I'm able to add the following to my module to add the PF2E namespace, allowing me to avoid having to typecast CONFIG to the any type (since you can't access properties on the `unknown` type).
Example override in a local definition file after the change:
```typescript
interface CONFIG {
PF2E: {
damageTypes: Record<string, string>;
}
}
```
> Make CONFIG a namespace to allow declaration merging

- foundry/applications/sidebarTabs/combatTracker.d.ts
- foundry/clientSettings.d.ts
- foundry/entities/combat.d.ts
- test-d/foundry/clientSettings.test-d.ts
Determines the type to use for ClientSettings.register by checking if it
is defined in ClientSettings.Values. If it is, pass the type as a type
param to ClientSettings.PartialSetting<T> and type check according to
that. If it is not defined in Values, derive the type param for
PartialSetting based on the supplied data object.
Updates PartialSetting to be a little more robust about what type is
passed in. For example, PartialSetting<boolean> has a type of
ConstructorOf<Boolean> for the type field.
Adds testing to verify that augmentation of ClientSettings.Values
results in an authoritative typing of the fields.
> Use an alternate approach to defining types for ClientSettings

- foundry/localization.d.ts
Some code I'm updating to Typescript was throwing an error about a missing argument so I looked into it and it's not a required argument
> Make the second argument of 1i8n.format optional in 0.7.9

- src/foundry/roll.d.ts
- src/foundry/rollTerms/poolTerm.d.ts
- Added overloads for `Roll.evaluate()` since it can return a promise if `async = true` is passed as an argument
- Added overloads for `Roll.reroll()`, see above
Changed type of `PoolTerm#rolls` as it should only contain roll, see https://discord.com/channels/170995199584108546/841367638180364348/844610476150227005
> 0.8.3/PoolTerm/Roll updates

- .eslintrc.js
- foundry/avMaster.d.ts
- foundry/pixi/containers/canvasLayers/placeablesLayers/lightingLayer.d.ts
- foundry/pixi/containers/placeableObjects/drawing.d.ts
- foundry/pixi/containers/placeableObjects/measuredTemplate.d.ts
- foundry/pixi/containers/placeableObjects/wall.d.ts
- foundry/pixi/texts/preciseText.d.ts
- foundry/ray.d.ts
- test-d/foundry/pixi/containers/placeableObject.test-d.ts
This adds the member-ordering and lines-between-class-members rules.
Accessors have to be sorted by hand, because the member-ordering rule
does not support those.
Ordering for accessors for future reference:
- static before constructor, instance after constructor
- after fields, before methods
- normal public, protected, private order
- getters before setters (grouped in pairs)
- sorted alphabetically
> Add two new eslint rules and fix some errors

- src/foundry/roll.d.ts
A small correction to the signature of `Roll.fromTerms`
> Options object of Roll.fromTerms has been made optional

- package-lock.json
- package.json
This will let us use branches directly as work is done on them. Prepare only runs for local installs not as a dependency. Does not work on Yarn 2, since they removed prepare from Yarn 1.
If you want to test it `git config --local --get core.hookspath` should show the hooks directory and `git config --local --unset core.hookspath` will remove it. Check it, unset it, check again (errors, exit code 1), `npm i`, check and it's set again.
If you want a repo to test with, I've started my 0.8.x update branch for SNWR, and use [this very branch for it](https://github.com/Spice-King/foundry-swnr/blob/65a2205b04816babee90b221f641fa346383317f/package.json#L21).
> Fix running husky when installed as a dependency

- src/foundry/common/abstract/document.mjs.d.ts
- test-d/foundry/common/abstract/document.mjs.test-d.ts
Signature of the method is `testUserPermission(user, permission, {exact=false}={})`
> Mark the third parameter of testUserPermission as optional

- src/foundry/common/utils/helpers.mjs.d.ts
- test-d/foundry/common/utils/helpers.mjs.test-d.ts
The current types of `mergeObject` are quite simple and does not even support the examples from the documentation.
I tried to get them more close to the implementation (which makes the implementation quite complex). This PR might not be perfect, but perhaps we can start from this to get a good solution.
> Enhance typing for mergeObject

- src/foundry/common/data/data.mjs/actorData.d.ts
- src/foundry/common/data/data.mjs/itemData.d.ts
- test-d/foundry/common/data/data.mjs/actorData.test-d.ts
- test-d/foundry/common/data/data.mjs/itemData.test-d.ts
Additionally, remove the generic DocumentData constructor function from the ItemData and ActorData constructors.
> Add tests for ActorData and ItemData

- .github/workflows/release.yml
- index.d.ts
- package-lock.json
- package.json
- src/foundry/common/abstract/backend.mjs.d.ts
- src/foundry/common/abstract/data.mjs.d.ts
- src/foundry/common/data/data.mjs/prototypeTokenData.d.ts
- src/foundry/foundry.js/applications/basePlaceableHUD.d.ts
- src/foundry/foundry.js/applications/basePlaceableHUDs/tokenHUD.d.ts
- src/foundry/foundry.js/applications/formApplication.d.ts
- src/foundry/foundry.js/applications/sceneControls.d.ts
- src/foundry/foundry.js/audioHelper.d.ts
- src/foundry/foundry.js/collections/documentCollections/compendiumCollection.d.ts
- src/foundry/foundry.js/config.d.ts
- src/foundry/foundry.js/formDataExtended.d.ts
- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/drawingsLayer.d.ts
- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/wallsLayer.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/ambientSound.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/token.d.ts
- src/foundry/foundry.js/textEditor.d.ts
- src/types/augments/howler.d.ts
- src/types/augments/index.d.ts
- src/types/augments/simple-peer.d.ts
- src/types/augments/tinyMCE.d.ts
- test-d/foundry/foundry.js/pixi/containers/placeableObject.test-d.ts
This updates all of our dev dependencies to the latest version and all dependencies of foundry to the corresponding version used in foundry, except for PIXI.
The formatting changes are due to the update of prettier and related dependencies. It now seems to have a different opinion on how a few things should be formatted.
Closes #846
> 0.8.x/update dependencies

- src/foundry/common/abstract/document.mjs.d.ts
- src/foundry/common/data/data.mjs/combatData.d.ts
- src/foundry/common/documents.mjs/baseActiveEffect.d.ts
- src/foundry/common/documents.mjs/baseActor.d.ts
- src/foundry/common/documents.mjs/baseChatMessage.d.ts
- src/foundry/common/documents.mjs/baseCombat.d.ts
- src/foundry/common/documents.mjs/baseCombatant.d.ts
- src/foundry/common/documents.mjs/baseDrawing.d.ts
- src/foundry/common/documents.mjs/baseFogExploration.d.ts
- src/foundry/common/documents.mjs/baseItem.d.ts
- src/foundry/common/documents.mjs/baseMacro.d.ts
- src/foundry/common/documents.mjs/baseTableResult.d.ts
- src/foundry/common/documents.mjs/baseWall.d.ts
- src/foundry/common/packages.mjs/packageData.d.ts
- src/foundry/foundry.js/canvasDocumentMixin.d.ts
- src/foundry/foundry.js/clientDocumentMixin.d.ts
- src/foundry/foundry.js/clientDocuments/activeEffect.d.ts
- src/foundry/foundry.js/clientDocuments/actor.d.ts
- src/foundry/foundry.js/clientDocuments/chatMessage.d.ts
- src/foundry/foundry.js/clientDocuments/combat.d.ts
- src/foundry/foundry.js/clientDocuments/folder.d.ts
- src/foundry/foundry.js/clientDocuments/item.d.ts
- src/foundry/foundry.js/collections/documentCollections/compendiumCollection.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/playlists.d.ts
- src/types/helperTypes.ts
- test-d/foundry/common/abstract/document.mjs.test-d.ts
- test-d/foundry/foundry.js/clientDocumentMixin.test-d.ts
Additionally, this ensures that Document#create and similar methods can be used with _source data.
> Ad a more readable way to extract constructor data from DocumentData.

- src/foundry/foundry.js/applications/sceneControls.d.ts
- test-d/foundry/foundry.js/applications/sceneControls.test-d.ts
Wanted to close #715, but it looks like the types were actually correct, just the order diverged from foundry. I resolved this, opened an [issue about the invalid documentation](https://gitlab.com/foundrynet/foundryvtt/-/issues/5596) and updated `SceneControls` (missing constructor and no configurable options).
Resolves #715
> Get SceneControls closer to the source code

- src/foundry/foundry.js/clientDocuments/chatMessage.d.ts
- test-d/foundry/foundry.js/clientDocuments/chatMessage.test-d.ts
Rather than fully rehashing this [you can read it here](https://discord.com/channels/732325252788387980/793933527065690184/863969310217207868), but short of it is that it does not really need a ChatMessageData, and works fine with the flatter instance of ChatMessageDataConstructorData, so I've made it a touch more flexible about what it accepts and returns the right thing in both cases.
> Update ChatMessage#applyRollMode to be more permissive.

- src/foundry/common/abstract/data.mjs.d.ts
- src/foundry/common/abstract/document.mjs.d.ts
- src/foundry/foundry.js/clientDocuments/canvasDocuments/tokenDocument.d.ts
- src/types/utils.d.ts
- test-d/types/utils.test-d.ts
It is not as smart as I hoped it would be, but if I didn't overlook anything, it seems to work:
This PR adds a Type `StoredDocument<D>` and it's counterpart `TemporaryDocument<D>` (which is just used as return-type for cloning). Sincerely, I could not find a way without modifying `Document`, but it should not affect the original documents.
It could be used to type things like `game.user` or `canvas.scene`.
> Distinguish between stored documents and temporary ones

- src/foundry/foundry.js/applications/dialog.d.ts
- test-d/foundry/foundry.js/applications/dialog.test-d.ts
This also refactors Dialog.prompt() and Dialog.confirm() to be closer to the source code.
Resolves #959
> Add rejectClose to Dialog.prompt

- src/foundry/foundry.js/pixi/texts/preciseText.d.ts
Resolves #807 
(To be fair, it was already resolved, but the constructor was missing.)
> PreciseText → 0.8.8

- src/foundry/foundry.js/avClient.d.ts
- src/foundry/foundry.js/avClients/easyRTCClient.d.ts
- src/foundry/foundry.js/avClients/index.d.ts
- src/foundry/foundry.js/avClients/simplePeerAVClient.d.ts
- src/foundry/foundry.js/avMaster.d.ts
- src/foundry/foundry.js/avSettings.d.ts
- src/foundry/foundry.js/config.d.ts
- src/foundry/index.d.ts
- src/types/augments/simple-peer.d.ts
- src/types/utils.d.ts
- test-d/foundry/avSettings.test-d.ts
- test-d/foundry/foundry.js/avMaster.test-d.ts
Closes #872
Closes #873
Closes #744
Also makes the used `AVClient` class type configurable and makes it possible to override the type of `AVSettings.VOICE_MODES`.
> Update AV related classes

- src/foundry/common/data/data.mjs/journalEntryData.d.ts
- src/foundry/foundry.js/collections/documentCollections/compendiumCollection.d.ts
- test-d/foundry/foundry.js/collections/documentCollections/compendiumCollection.test-d.ts
The `IndexTypeForMetadata` has invalid properties configured and did not use `StoredDocument` while the rest of the `CompendiumCollection` does.
It also fixes a small issue of `JournalEntryData` where the `img` property was marked invalid.
See [here](https://github.com/League-of-Foundry-Developers/foundry-vtt-types/pull/1178/checks?check_run_id=3600635096) for the result of the failing tests.
> Fix IndexTypeForMetadata of CompendiumCollection

- src/foundry/foundry.js/applications/formApplications/documentSheets/macroConfig.d.ts
- test-d/foundry/foundry.js/applications/formApplications/documentSheets/macroConfig.test-d.ts
`MacroConfig.Options` exists just to be more consistent with other documents.
Resolves #373
> Update MacroConfig to 0.8.9

- src/foundry/foundry.js/config.d.ts
- test-d/foundry/foundry.js/clientDocuments/activeEffect.test-d.ts
Adds the flag used to tell if an ActiveEffect is considered a status
effect, which controls if the effect is shown as an icon on the token.
Adds the flag used to tell if an ActiveEffect is considered an overlay
effect, which displays over the token image.
> Add core ActiveEffect flags to FlagConfig

- .github/workflows/checks.yml
- .github/workflows/release.yml
- package-lock.json
- package.json
- src/foundry/common/utils/helpers.mjs.d.ts
- src/foundry/foundry.js/application.d.ts
- src/foundry/foundry.js/applications/basePlaceableHUD.d.ts
- src/foundry/foundry.js/applications/formApplications/gridConfig.d.ts
- tsconfig.json
This updates our dependencies and prepares our codebase for the case
when users want to use the new exactOptionalPropertyTypes compiler
option.
Surprisingly there was just one place where I needed to change something.
> Update dependencies and prepare for exactOptionalPropertyTypes option

- src/foundry/foundry.js/textureLoader.d.ts
Closes #461
Note that I intentionally left out the `message` parameter of `_onProgress`, see https://gitlab.com/foundrynet/foundryvtt/-/issues/5888
> Update TextureLoader for 0.8.9

- src/foundry/foundry.js/clientDocuments/combat.d.ts
According to Atropos, these parameters are meant to be publicly
readable. Ref:
https://discord.com/channels/170995199584108546/811676497965613117/892110168450547763
> Remove protected annotation from Combat#current and Combat#previous

- src/foundry/foundry.js/clientSettings.d.ts
- test-d/foundry/foundry.js/applications/sidebarTabs/combatTracker.test-d.ts
- test-d/foundry/foundry.js/clientSettings.test-d.ts
This happens when the user never touched the combat settings since world
creation. In that case, the setting just returns an empty object.
> Add uninitialized combat config type

- src/foundry/foundry.js/application.d.ts
I believe the intended use of `Application._renderOuter` is exemplified by something like the following.
```ts
protected async _renderOuter() {
const element = await super._renderOuter();
$(element).addClass("FOO");
return element;
}
```
However, the return type -- a union of two different `Promise<T>` types -- causes the code above to fail at compile time.
```
TS2416: Property '_renderOuter' in type 'MyDialog' is not assignable to the same property in base type 'Dialog<Options>'.
Type '() => Promise<HTMLElement | JQuery<Node>>' is not assignable to type '() => Promise<HTMLElement> | Promise<JQuery<Node>>'.
Type 'Promise<HTMLElement | JQuery<Node>>' is not assignable to type 'Promise<HTMLElement> | Promise<JQuery<Node>>'.
Type 'Promise<HTMLElement | JQuery<Node>>' is not assignable to …
```
> fix return type of Application._renderOuter

- src/foundry/foundry.js/clientDocuments/actor.d.ts
- src/foundry/foundry.js/clientDocuments/item.d.ts
- test-d/foundry/foundry.js/clientDocuments/item.test-d.ts
Motivation: Systems that extend `Item` and `Actor` frequently break polymorphism. The very frequent case of `data.data` and `data._source` has already been accounted for with `DataConfig` and `SourceConfig` respectively. However `getRollData()` also is not always polymorphic to `this.data.data` like it's currently typed as. Most notably Atropos's own D&D 5e implementation has [Actor5e#getRollData()](https://gitlab.com/foundrynet/dnd5e/-/blob/1db8dfe5b8126ba2efb98f5daff3932a0bd94f1a/module/actor/entity.js#L197-206) and [Item5e#getRollData()](https://gitlab.com/foundrynet/dnd5e/-/blob/1db8dfe5b8126ba2efb98f5daff3932a0bd94f1a/module/item/entity.js#L1324-1345) which aren't even bivariant.
Implementation:
Similar to the aforementioned `DataConfig` and `SourceConfig`, this PR adds …
> Add in configuration for getRollData()

- src/foundry/common/types.mjs.d.ts
While working on keybindings, I noticed that the functions do not have the `KeyboardEventContext` that is available to these functions
> Add KeyboardEventContext to KeybindingActionConfig.onDown and KeybindingActionConfig.onUp

- src/foundry/common/data/data.mjs/index.d.ts
- src/foundry/foundry.js/applications/formApplications/avConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/combatTrackerConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/ambientLightConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/ambientSoundConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/combatantConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/folderConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/journalSheet.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/macroConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/measuredTemplateConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/noteConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/playlistSoundConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/rollTableConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/sceneConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/tileConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/userConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/drawingConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/entitySheetConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/gridConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/index.d.ts
- src/foundry/foundry.js/applications/formApplications/moduleManagement.d.ts
- src/foundry/foundry.js/applications/formApplications/permissionConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/settingsConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/tokenConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/tokenConfigs/defaultTokenConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/tokenConfigs/index.d.ts
- src/foundry/foundry.js/applications/formApplications/wallConfig.d.ts
Closes #1392
Additionally, this also changes the return type of _updateObject to Promise<unknown> for
every FormApplication, as the concrete return type is not supposed to be used.
> Update DefaultTokenConfig for v9

- src/foundry/client/ui/dialog.d.ts
Often times I leave off `default` if I want to ensure the user makes a conscious decision. I figure it should be optional to allow for this.
> Make 'default' property in dialog data optional

- src/foundry/client/av/settings.d.ts
canBroadCastAudio should be canBroadcastAudio to match FoundryVTT
> AVSettings: Fix UserSettings typo

- src/foundry/client/apps/forms/effect-config.d.ts
- test-d/foundry/client/apps/forms/effect-config.test-d.ts
While #1795 fixed the mode type, I should've probably also reflected that in the Active Effect Config 💁‍♂️
> Relax "modes" type in Effect Config Data

- src/types/utils.d.ts
- test-d/types/utils.test-d.ts
Added `MaybePromise` type to clean up places that may potentially return either a value or a promise to said value. No changes were done, since @ghost91- was working on the one place it would be used.
Removed unused `PromisedType`, which got replaced with TS 4.5's `Awaited`.
> Minor Utils TLC

- src/foundry/client/ui/dialog.d.ts
- test-d/foundry/client/ui/dialog.test-d.ts
* resolves #2214
This changeset introduces the following major changes:
* Add new `disabled` property to `Dialog.Button`
* Remove static qualification of `Dialog.title`. From what I can tell, even in V9 this was not static.
* Update `Dialog.getData` to always return an object and not a `MaybePromise`. This is the documented behavior in the V10 API docs and, as far as I can tell, also the implementation behavior. Referring back to V9 again, this was also the case back then, it just wasn't documented that way in the V9 API docs.
* Add an `event` parameter to `Dialog.submit`. Interestingly enough, there seems to be an inconsistency between the V10 API doc and the actual implementation. According to the docs, `Dialog.submit` can receive an optional `event` parameter of type `PointerEvent`. …
> V10 Typings: update Dialog

- src/foundry/client/apps/forms/card-config.d.ts
resolves: #1863 
This changeset introduces the following major changes:
* Remove `CardConfig._getSubmitData` as it is no longer present in `CardConfig` in V10 (as in it is no longer overridden by the implementation, it is of course still part of the base `FormApplication`).
* Retype `CardConfig._onFaceControl` to return `Promise<unknown>` instead of `Promise<void>`. The actual implementation returns either the result of updating the `Card` objects (which would yield `Promise<Card>` or more precisely `Promise<InstanceType<ConfiguredDocumentClassForName<"Card">>`) or the result of `Dialog.confirm`. The API documentation describes it as returning `Promise<any>`, which seems unnecessarily open. I am a bit conflicted on whether or not we should return the actual precise types. I feel that it …
> V10 typings: update CardConfig

- package-lock.json
- package.json
In order to not trigger the install of Husky when the types are used as a dependency the execution of the prepare script has been tied to the is-ci package
> Added is-ci package to suppress husky in pipelines

- src/foundry/client/apps/forms/effect-config.d.ts
> ActiveEffectConfig

- src/foundry/client/apps/forms/ownership.d.ts
- src/foundry/client/apps/hud/chatbubble.d.ts
- src/foundry/client/tours/setup-tour.d.ts
- src/types/augments/tinyMCE.d.ts
- tsconfig.json
So the tsconfig option `skipLibCheck` skips type checking all `.d.ts` files. This fixed the TinyMCE augments but it also silenced the type checking in every single `.d.ts` file we had, that is to say basically _all_ our Typescript files. This should fix that.
> Re-enable lib check and fix hidden errors

- src/foundry/client/apps/sidebar/apps/invitation-links.d.mts
- src/foundry/client/apps/sidebar/apps/keybindings-config.d.mts
- src/foundry/client/apps/sidebar/apps/module-management.d.mts
- src/foundry/client/apps/sidebar/apps/permission-config.d.mts
- src/foundry/client/apps/sidebar/apps/support-details.d.mts
- src/foundry/client/apps/sidebar/apps/tours-management.d.mts
- src/foundry/client/apps/sidebar/package-configuration.d.mts
Haven't touched world config yet, but all the rest are here. Open questions:
- `categoryOrder` inherits the exact return type definition of a specific string array (just in the type documentation), but we know it's different because it adds one in at index 2. Anything we need to change there?
- the new `CategoryData` interface I've made in `package-configuration`; should categories be `Category[]` or `object[]`?
- Not sure I got the `ModuleManagement` constructor right
- What about `ModuleManagement`'s `_renderInner`? It takes `...args` but eventually that just becomes `data`
Lemme know what I need to fix!
> Sidebar apps

- src/foundry/client/apps/sidebar/tabs/actors-directory.d.mts
- src/foundry/client/apps/sidebar/tabs/cards-directory.d.mts
- src/foundry/client/apps/sidebar/tabs/chat-log.d.mts
- src/foundry/client/apps/sidebar/tabs/combat-tracker.d.mts
- src/foundry/client/apps/sidebar/tabs/compendium-directory.d.mts
- src/foundry/client/apps/sidebar/tabs/items-directory.d.mts
- src/foundry/client/apps/sidebar/tabs/journal-directory.d.mts
- src/foundry/client/apps/sidebar/tabs/macros-directory.d.mts
- src/foundry/client/apps/sidebar/tabs/playlists-directory.d.mts
- src/foundry/client/apps/sidebar/tabs/roll-table-directory.d.mts
- src/foundry/client/apps/sidebar/tabs/scenes-directory.d.mts
- src/foundry/client/apps/sidebar/tabs/settings.d.mts
Only real question here is whether I handled the playlist `unknown` -> `Promise<InstanceType<ConfiguredDocumentClass<typeof Playlist>>>` stuff right. I'm certain they return a `Playlist` type object, but not certain I've properly copy/pasted the appropriate types (i.e. vs just making them return `Promise<Playlist>`
> sidebar tabs

- package-lock.json
- package.json
- patches/@types+earcut+2.1.4.patch
- src/foundry/index.d.mts
- src/foundry/public/index.d.mts
- src/foundry/public/scripts/earcut-edges/earcut-edges.d.mts
- src/foundry/public/scripts/earcut-edges/index.d.mts
- src/foundry/public/scripts/index.d.mts
- tests/foundry/public/scripts/earcut-edges/earcut-edges.test-d.ts
should resolve #2185 
Additions to `package.json`:
- `patch-package` module, allows us to patch the dependency `@types/earcut` post install
- `postinstall-postinstall` module, necessary for the above to work in yarn v1 (and makes it so the patch happens when `npm install` is used _in this project_ for developing)
- the actual `postinstall` script which will initiate the patch for npm and yarn v1
- `resolutions` section which _should_ initiate the patch for yarn v2
> earcut and patching for earcut

- src/foundry/common/primitives/math.d.mts
- src/foundry/common/primitives/number.d.mts
- src/foundry/common/primitives/string.d.mts
- tests/foundry/common/primitives/math.mjs.test-d.ts
Solves #2587, #2586,  and #2585.
- Adds SQRT3 and SQRT1_3 values.
- Adds Math.clamp.
- Deprecates Math.clamped.
- Deprecates Math.normalizeDegrees with the base parameter.
- Removes Math.fastRound.
- Adds compare function.
- Updates function definition text.
> Updates `string.mjs`, `number.mjs`, and `math.mjs`

- src/foundry/client/ui/editor.d.mts
- src/foundry/common/abstract/type-data.d.mts
- tests/foundry/common/abstract/type-data.mjs.test-d.ts
- tests/foundry/common/documents/actor.test-d.ts
Solves #2579 .
- added hook functions
- Added the `DocumentHTMLEmbedConfig` type in editor
- changed the type of `this` in `prepareBaseData`, as the documentation indicates that derived data should not be computed or present at this step (I might be wrong on this, please advise).
> common.abstract.type-data

- src/foundry/common/types.d.mts
- src/foundry/common/utils/color.d.mts
Solves #2602
Would have loved to type the numeric values in the various array types to be [0..1], but unfortunately, [it's not that simple](https://github.com/microsoft/TypeScript/issues/54925).
> common.utils.colors

- src/foundry/common/utils/iterable-weak-set.d.mts
- tests/foundry/common/utils/iterable-weak-set.test-d.ts
Added method clear() to iterable weak set, and test for signature return value to make sure it's there.
>  Update iterable-weak-set.mjs #2607

- src/foundry/common/constants.d.mts
- src/types/helperTypes.d.mts
- Adding missing array declaration in CONST
- Adjusted helperTypes to minimize how many places we declare these things now that Foundry has more comprehensive support
Closes #2632
> Adjusted Document helper types

- src/foundry/common/utils/iterable-weak-map.d.mts
- tests/foundry/common/utils/iterable-weak-map.test-d.ts
Very similar to weak-set, source have added clear() method, removed javascript `#private` props.
>  Update iterable-weak-map.mjs #2606

- src/foundry/client/data/documents/active-effect.d.mts
Updates `ActiveEffect` to v12.
Changes 
```ts
get target(): Actor | null; 
```
to 
```ts
get target(): Document | null;
```
There was a TODO there to make the return type more generic. There are a bunch of systems that specifically target `Item` and `TokenDocument`.
> Update `ActiveEffect` to v12

- src/foundry/client/config.d.mts
- src/foundry/client/data/abstract/client-document.d.mts
- src/foundry/client/ui/editor.d.mts
Also included significant type fixes to TextEditor now that I understand partials better :)
(a v11 backport would also want to tackle changing all the MaybePromise into using EnrichmentOptions as a generic to discriminate promise & non-promise returns)
Resolves #2725 and #2679
> Updated ClientDocument and TextEditor to v12

- src/foundry/client/data/abstract/canvas-document.d.mts
- v12 added _preCreate
- None of these functions impact signatures, they're all just executing side effects (e.g. drawing the associated `object`)
- Closes #2726
> Removed CanvasDocument event handlers

- src/foundry/client/data/abstract/client-document.d.mts
- src/foundry/common/abstract/document.d.mts
Tests are broken due to field issues but I did my best to match our existing styles and not introduce any new bad types.
Something to consider is if the various references to `User` should change from `foundry.documents.BaseUser` to `User.ConfiguredInstance`, since that's what devs will actually be working with in the client even though the Foundry types are less presumptuous.
Another consideration is what we want to do with DocumentModificationContext; Foundry doesn't actually provide the type of the `options` object passed as an argument in `_preCreate` et al.
> Updated Document to v12

- src/foundry/client-esm/applications/api/document-sheet.d.mts
- src/foundry/client/apps/form.d.mts
- src/foundry/client/apps/forms/image-popout.d.mts
- src/foundry/client/apps/forms/ownership.d.mts
- src/foundry/client/apps/forms/sheet-config.d.mts
- src/foundry/client/core/document-index.d.mts
- src/foundry/client/core/utils.d.mts
- src/foundry/client/data/abstract/client-document.d.mts
- src/foundry/client/hooks.d.mts
- src/foundry/client/ui/secrets.d.mts
- src/foundry/common/abstract/embedded-collection-delta.d.mts
- src/foundry/common/types.d.mts
Simple find and replace, left out the handful of uses in prosemirror since those are handled in #2739
> Replaced all instances of Document<any, any, any> with Document.Any

- src/foundry/client/apps/forms/grid-config.d.mts
Part of #2546
We migrate `GridConfig#getData` to use `GetDataReturnType`. We're
following the pattern laid out in the other subclasses of `Application`.
- Addition: Added `GridConfig.GridConfigData`.
- Breaking: The return type of `GridConfig#getData` is more precise now.
> Use `GetDataReturnType` in `GridConfig`

- src/foundry/client/data/abstract/document-collection.d.mts
- src/foundry/client/data/abstract/world-collection.d.mts
- src/foundry/common/abstract/socket.d.mts
- DirectoryCollectionMixin did not need updates
- Foundry formally implemented `FromCompendiumOptions` as a typedef themselves, but we had already abstracted it out with a matching name.
Closes #2874
> Updated `client/data/abstract`

- src/foundry/client/pixi/layers/grid/layer.d.mts
Too many other inheritance based issues with GridLayer.instance pointing to a BaseGrid rather than GridLayer instance, especially with CONFIG
> Fixed error in GridLayer.instance

- src/foundry/client/hooks.d.mts
- src/foundry/client/pixi/groups/primary.d.mts
> Updated Hooks to v12

- package-lock.json
- src/foundry/client-esm/applications/api/application.d.mts
- src/foundry/client-esm/applications/sheets/ambient-light-config.d.mts
- src/foundry/client-esm/applications/sheets/ambient-sound-config.d.mts
- src/foundry/client-esm/applications/sheets/user-config.d.mts
- tests/foundry/client/data/collections/users.test-d.ts
Completes non-region work on #2612 
question; these classes have several private functions, primarily for their `actions` but also to help context prep. Should I include a `#private` property on the classes for duck typing purposes?
> AmbientLightConfig, AmbientSoundConfig, UserConfig implementations

- src/foundry/client/config.d.mts
- src/types/helperTypes.d.mts
- src/types/utils.d.mts
Removed duplicate type from `helperTypes`, broadened type params to `extends object` to allow for taking interfaces directly.
> HandleEmptyObject deduped and broadened

- src/foundry/client/hooks.d.mts
- src/foundry/common/utils/helpers.d.mts
Ran into two type bugs caused by global namespace
> Bad global type bugs

- src/foundry/client-esm/applications/forms/fields.d.mts
Might have accidentally lost the function in the refactor? IDK what it was but was trying to use the function and noticed it wasn't in the types.
> Added createSelectInput

- src/foundry/client/data/abstract/world-collection.d.mts
- src/foundry/client/pixi/core/interaction/canvas-animation.d.mts
- src/foundry/client/pixi/core/interaction/control-icon.d.mts
- src/foundry/client/pixi/core/interaction/mouse-handler.d.mts
- src/foundry/client/pixi/core/interaction/ping.d.mts
- src/foundry/client/pixi/core/interaction/pings/chevron.d.mts
- src/foundry/client/pixi/core/interaction/pings/pulse.d.mts
- src/foundry/client/pixi/core/interaction/resize-handle.d.mts
- src/foundry/client/pixi/core/interaction/targets.d.mts
- src/types/augments/pixi.d.mts
- src/utils/index.d.mts
- tests/foundry/client/pixi/board.test-d.ts
- tests/foundry/client/pixi/core/interaction/canvas-animation.test-d.ts
- tests/foundry/client/pixi/core/interaction/control-icon.test-d.ts
- tests/foundry/client/pixi/core/interaction/mouse-handler.test-d.ts
- tests/foundry/client/pixi/core/interaction/ping.test-d.ts
- tests/foundry/client/pixi/core/interaction/pings/chevron.test-d.ts
- tests/foundry/client/pixi/core/interaction/pings/pulse.test-d.ts
- tests/foundry/client/pixi/core/interaction/resize-handle.test-d.ts
- tests/foundry/client/pixi/core/interaction/targets.test-d.ts
Touched up everything in the title folder except RenderFlags, as that has had recent attention and what I can decode of it looks accuate
> Touchup of `client/pixi/core/interaction/**` and associated side effects

- package-lock.json
- package.json
- src/foundry/client/pixi/workers/texture-worker.d.mts
- src/foundry/public/scripts/workers/image-compressor.d.mts
- src/foundry/public/scripts/workers/index.d.mts
- src/types/workers/image-compressor.d.mts
- tests/foundry/public/scripts/workers/image-compressor.test-d.ts
Adds a new dependency (`@pixi/basis`) and a new export path (`worker`) to package.json
> Types and tests for `client/pixi/workers/**` and `public/scripts/workers/**`

- src/foundry/common/prosemirror/_module.d.mts
- src/foundry/common/prosemirror/schema/lists.d.mts
- tests/foundry/common/prosemirror/_module.test-d.ts
- tests/foundry/common/prosemirror/click-handler.test-d.ts
- tests/foundry/common/prosemirror/content-link-plugin.test-d.ts
- tests/foundry/common/prosemirror/dirty-plugin.test-d.ts
- tests/foundry/common/prosemirror/dom-parser.test-d.ts
- tests/foundry/common/prosemirror/dropdown.test-d.ts
- tests/foundry/common/prosemirror/extensions.test-d.ts
- tests/foundry/common/prosemirror/highlight-matches-plugin.test-d.ts
- tests/foundry/common/prosemirror/image-plugin.test-d.ts
- tests/foundry/common/prosemirror/input-rules.test-d.ts
- tests/foundry/common/prosemirror/keymaps.test-d.ts
- tests/foundry/common/prosemirror/menu.test-d.ts
- tests/foundry/common/prosemirror/paste-transformer.test-d.ts
- tests/foundry/common/prosemirror/plugin.test-d..ts
- tests/foundry/common/prosemirror/prosemirror.test-d.ts
- tests/foundry/common/prosemirror/schema/attribute-capture.test-d.ts
- tests/foundry/common/prosemirror/schema/core.test-d.ts
- tests/foundry/common/prosemirror/schema/image-link-node.test-d.ts
- tests/foundry/common/prosemirror/schema/image-node.test-d.ts
- tests/foundry/common/prosemirror/schema/link-mark.test-d.ts
- tests/foundry/common/prosemirror/schema/lists.test-d.ts
- tests/foundry/common/prosemirror/schema/other.test-d.ts
- tests/foundry/common/prosemirror/schema/schema-definition.test-d.ts
- tests/foundry/common/prosemirror/schema/secret-node.test-d.ts
- tests/foundry/common/prosemirror/schema/tables.test-d.ts
- tests/foundry/common/prosemirror/schema/utils.test-d.ts
- tests/foundry/common/prosemirror/string-serializer.test-d.ts
- tests/foundry/common/prosemirror/util.test-d.ts
Please pay particular attention to the imports that I changed in /common/prosemirror/_module.d.mts
Those should be classes that are available as properties of both `fo;undry.prosemirror` and `ProseMirror`.  I think I did it correctly (and the tests pass), but just wanted to make sure it wasn't going to break something else.
> Prosemirror tests

- src/foundry/client/applications/handlebars.d.mts
- tests/foundry/client/applications/handlebars.test-d.ts
I honestly wonder if I had just missed the `object` addition, but the ifThen is definitely new.
Follow-up question; should/could we export the helper interfaces? If so I can add that to this pR
> Updated Handlebars to 13.346

- src/foundry/client/packages/module.d.mts
- src/foundry/client/packages/system.d.mts
- src/foundry/common/packages/base-package.d.mts
- src/foundry/common/packages/sub-types.d.mts
- tests/foundry/common/packages/base-module.test-d.ts
- tests/foundry/common/packages/base-system.test-d.ts
Remaining question is how to handle the PackageFlagsData
```js
/**
* @typedef PackageFlagsData
* Flags used by the core software.
* @property {boolean} canUpload Can you upload to this package's folder using the built-in FilePicker.
* @property {object} hotReload Configuration information for hot reload logic
* @property {string[]} hotReload.extensions A list of file extensions, e.g. `["css", "hbs", "json"]`
* @property {string[]} hotReload.paths File paths to watch, e.g. `["src/styles", "templates", "lang"]`
* @property {Record<string, CompendiumArtFlag>} compendiumArtMappings Mapping information for CompendiumArt
*                                      Each key is a unique system ID, e.g. "dnd5e" or "pf2e".
* @property {Record<string, string>} tokenRingSubjectMappings A mapping of token …
```
> Type Annotations for Packages
