- types/framework/entities/item.d.ts
> Get rid of circular reference

- index.d.ts
- package-lock.json
- types/applications/forms/item.d.ts
- types/augments/utility-types.d.ts
- types/framework/collection.d.ts
- types/framework/entities/activeEffect.d.ts
- types/framework/entities/actor.d.ts
- types/framework/entities/chatMessage.d.ts
- types/framework/entities/combat.d.ts
- types/framework/entities/folder.d.ts
- types/framework/entities/item.d.ts
- types/framework/entities/journal.d.ts
- types/framework/entities/macro.d.ts
- types/framework/entities/playlist.d.ts
- types/framework/entities/rollTable.d.ts
- types/framework/entities/scene.d.ts
- types/framework/entities/user.d.ts
- types/framework/entity.d.ts
- types/framework/entityCollection.d.ts
- types/typesUtils.d.ts
Additional updates to entities not covered by #3 .
> [RDY] More Entity updates

- .eslintrc.js
- .github/workflows/checks.yml
- package-lock.json
- package.json
- test-d/typesUtils.test-d.ts
- tsconfig.eslint.json
> Add testing capabilities using tsd

- index.d.ts
- types/framework/entities/user.d.ts
- types/framework/userTargets.d.ts
> Add UserTargets class

- test-d/game.test-d.ts
- types/game.d.ts
> Fix adding custom properties to Game

- types/core/config.d.ts
- types/core/settings/clientSettings.d.ts
- types/framework/entities/actor.d.ts
- types/framework/entities/item.d.ts
- types/framework/entity.d.ts
- types/typesUtils.d.ts
- types/utils.d.ts
Creates ConstructorOf to improve readability when passing or recieving a class. Also contains some minor updates to `CONFIG`.
> Create ConstructorOf<T> utility type

- types/core/config.d.ts
- types/pixi/pointSource.d.ts
This updates `CONFIG` to 0.7.9.
Additionally, it also updates `PointSource`. (Argh, I didn't notice that #243 also covers this, but I think I covered some stuff that seems to be missing in that PR).
When reviewing this, please consider some questions:
- Are you fine with the general approach of providing `@defaultValue`s for almost everything?
- What do you think about the fact that for most things, all default elements of objects are included (e.g. in `JournalEntry.noteIcons`)?
- What do you think about the fact that it's not done for some more difficult things (like `Canvas.lightAnimations`) and only a generic type is given instead?
- Where do you think the `Permisssion` interface should go? Are you fine with how `User.permissions` is currently set up?
Fixes #265
Fixes #240
Fixes #154
> Update CONFIG to 0.7.9

- tsconfig.json
- types/core/textEditor.d.ts
> Update TextEditor and update to ES2020

- types/framework/entities/combat.d.ts
Adds missing parameter defeated to Combatant
Updates combatant management methods
> Fix issues with combatants

- types/framework/entities/activeEffect.d.ts
- types/ui/activeEffectConfig.d.ts
> Add ActiveEffectConfig

- types/applications/hud/pause.d.ts
> Update Pause to 0.7.9

- types/applications/application.d.ts
- types/ui/notifications.d.ts
> Update Notifications to 0.7.9

- types/framework/entities/actor.d.ts
- types/framework/entity.d.ts
- types/pixi/placeableObjects/wall.d.ts
Using this['data'] has unintended side effects in subclasses, so simply
revert to using D or the specific data type.
> Reference Data directly

- types/applications/formApplication.d.ts
- types/applications/formDataExtended.d.ts
> Update FormDataExtended to 0.7.9

- types/framework/compendium.d.ts
> Update Compendium to 0.7.9

- foundry/config.d.ts
- foundry/specialEffect.d.ts
- foundry/specialEffects/autumnLeavesWeatherEffect.d.ts
- foundry/specialEffects/rainWeatherEffect.d.ts
- foundry/specialEffects/snowWeatherEffect.d.ts
- index.d.ts
- package-lock.json
- package.json
- types/augments/pixiParticles.d.ts
Fixes #200
Fixes #201
Fixes #202
Fixes #203
> Add classes related to special effects (weather effects)

- foundry/pixi/containers/ruler.d.ts
> Update Ruler to 0.7.9

- .github/workflows/checks.yml
- foundry/ray.d.ts
- package.json
Hopefully this fixes the forked PR failing checks
> Fix github actions for forked PRs

- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
This Pull Request sets the npm package version to `0.7.9-0` in preparation to out first release on npm. It also adjusts the the README.md accordingly and adds a file `CONTRIBUTING.md` with contributing guidelines.
> Update Readme, Contributing guidelines, and set version to 0.7.9-0

- .gitignore
- foundry/chatBubbles.d.ts
> Update ChatBubbles to 0.7.9

- foundry/application.d.ts
- foundry/applications/eula.d.ts
- index.d.ts
> Update EULA to 0.7.9

- foundry/applications/mainMenu.d.ts
> Update MainMenu to 0.7.9

- foundry/pixi/containers/canvasLayers/placeablesLayer.d.ts
- foundry/pixi/graphics/resizeHandle.d.ts
- foundry/pixi/rectangles/normalizedRectangle.d.ts
- foundry/quadtree.d.ts
- foundry/ray.d.ts
- index.d.ts
Tried to knockout a few unassigned ones, hopefully I'm not stepping on anyone's toes.
Resolves #150
Resolves #151
Resolves #152
Resolves #153
> Ray, ResizeHandle, NormalizedRectangle, QuadTree types for Foundry 0.7.9

- foundry/textureLoader.d.ts
- foundry/textureUtils.d.ts
- index.d.ts
> Update TextureLoader to 0.7.9

- foundry/canvas.d.ts
- foundry/pixi/containers/canvasLayer.d.ts
- foundry/pixi/containers/canvasLayers/backgroundLayer.d.ts
- foundry/pixi/containers/canvasLayers/controlsLayer.d.ts
- foundry/pixi/containers/canvasLayers/effectsLayer.d.ts
- foundry/pixi/containers/canvasLayers/placeablesLayer.d.ts
- foundry/pixi/containers/canvasLayers/placeablesLayers/drawingsLayer.d.ts
- foundry/pixi/containers/canvasLayers/placeablesLayers/lightingLayer.d.ts
- foundry/pixi/containers/canvasLayers/placeablesLayers/notesLayer.d.ts
- foundry/pixi/containers/canvasLayers/placeablesLayers/soundsLayer.d.ts
- foundry/pixi/containers/canvasLayers/placeablesLayers/templateLayer.d.ts
- foundry/pixi/containers/canvasLayers/placeablesLayers/tilesLayer.d.ts
- foundry/pixi/containers/canvasLayers/placeablesLayers/tokenLayer.d.ts
- foundry/pixi/containers/canvasLayers/placeablesLayers/wallsLayer.d.ts
- foundry/pixi/containers/canvasLayers/sightLayer.d.ts
- foundry/pixi/containers/cursor.d.ts
- foundry/pixi/containers/placeableObjects/ambientSound.d.ts
- foundry/types.d.ts
- index.d.ts
> Updates several canvas layers to 0.7.9

- foundry/canvasAnimation.d.ts
- index.d.ts
> Update CanvasAnimation to 0.7.9

- foundry/applications/frameViewer.d.ts
- foundry/collections/entityCollection.d.ts
- foundry/collections/entityCollections/combatEncounters.d.ts
- index.d.ts
Resolves #115 
Resolves #124 
Resolves #117
> Update FrameViewer, EntityCollection, and CombatEncounters to 0.7.9

- foundry/applications/sceneControls.d.ts
> Update SceneControls to 0.7.9

- foundry/applications/playerList.d.ts
Updated the Player List to match the 0.7.9 version of foundry.js, as like [here](https://foundryvtt.com/api/foundry.js.html#line21043)
Resolves issue #79
> Player List - Foundry 0.7.9

- foundry/applications/chatPopout.d.ts
- foundry/entities/chatMessage.d.ts
- index.d.ts
> Update ChatPopout to 0.7.9

- foundry/applications/updateNotes.d.ts
- index.d.ts
> Update UpdateNotes to 0.7.9

- foundry/actorTokenHelpers.d.ts
- foundry/applications/formApplications/baseEntitySheet.d.ts
- foundry/collections/entityCollection.d.ts
- foundry/entities/actor.d.ts
- foundry/entities/folder.d.ts
- foundry/entities/item.d.ts
- foundry/entities/scene.d.ts
- foundry/entity.d.ts
- test-d/foundry/entities/actor.test-d.ts
> Separate types of _data and data

- foundry/utils.d.ts
- test-d/foundry/applications/formApplications/baseEntitySheets/actorSheet.test-d.ts
- test-d/foundry/utils.test-d.ts
> Remove special handling of number in duplicate

- foundry/globals.d.ts
- index.d.ts
> Add global _token

- foundry/constants.d.ts
> Add BLEND_MODES

- foundry/collections/entityCollections/users.d.ts
> Solved issue : https://github.com/League-of-Foundry-Developers/foundry-vtt-types/issues/584

- foundry/applications/installPackage.d.ts
- index.d.ts
> Add InstallPackage to 0.7.9

- foundry/pixi/containers/doorControl.d.ts
> Add some missing door control properties

- src/foundry/pixi/containers/canvasLayers/gridLayer.d.ts
> Update GridLayer to 0.8.2

- src/foundry/rollTerm.d.ts
The documentation comment for this class was added in Foundry 0.8.4
> updated documentation for RollTerm class

- src/foundry/rollTerm.d.ts
- src/foundry/rollTerms/diceTerm.d.ts
- src/foundry/rollTerms/diceTerms/coin.d.ts
- src/foundry/rollTerms/diceTerms/die.d.ts
- src/foundry/rollTerms/diceTerms/fateDie.d.ts
- src/foundry/rollTerms/mathTerm.d.ts
- src/foundry/rollTerms/parentheticalTerm.d.ts
- src/foundry/rollTerms/poolTerm.d.ts
closes #799
closes #800
closes #801
closes #802
closes #803
Also applied new ordering rules to the changed files
> Updated RollTerms to 0.8.5

- README.md
- foundry/entities/macro.d.ts
- package-lock.json
- package.json
This PR also updates the version to 0.7.10-0. A release with this version should be performed after merging this PR as this is the only change related to 0.7.10.
> Add _executeScript to Macro

- src/foundry/foundry.js/clientDocuments/item.d.ts
Fixes #442
Only does things that are public, not deprecated, and not an override.
> Add methods and getters to Item

- src/foundry/common/documents.mjs/baseAmbientLight.d.ts
- src/foundry/foundry.js/canvasDocumentMixin.d.ts
- src/foundry/foundry.js/clientDocumentMixin.d.ts
- src/foundry/foundry.js/clientDocuments/canvasDocuments/ambientLightDocument.d.ts
- src/foundry/foundry.js/config.d.ts
- src/foundry/index.d.ts
- src/types/helperTypes.ts
- test-d/foundry/foundry.js/canvasDocumentMixin.test-d.ts
- test-d/foundry/foundry.js/clientDocumentMixin.test-d.ts
I'm not sure whether it is a step in the right direction or whether it is useful after all, so feel free to close it if not.
> CanvasDocumentMixin, BaseAmbientLight, AmbientLightDocument

- src/foundry/common/abstract/backend.mjs.d.ts
- src/foundry/common/abstract/data.mjs.d.ts
- src/foundry/common/abstract/document.mjs.d.ts
- src/foundry/common/abstract/embedded-collection.mjs.d.ts
- src/foundry/common/data/data.mjs/activeEffectData.d.ts
- src/foundry/common/data/data.mjs/ambientLightData.d.ts
- src/foundry/common/data/data.mjs/animationData.d.ts
- src/foundry/common/data/data.mjs/darknessActivation.d.ts
- src/foundry/common/data/data.mjs/effectChangeData.d.ts
- src/foundry/common/data/data.mjs/effectDurationData.d.ts
- src/foundry/common/data/data.mjs/folderData.d.ts
- src/foundry/common/data/data.mjs/itemData.d.ts
- src/foundry/common/data/data.mjs/journalEntryData.d.ts
- src/foundry/common/data/data.mjs/macroData.d.ts
- src/foundry/common/documents.mjs/baseActiveEffect.d.ts
- src/foundry/common/documents.mjs/baseItem.d.ts
- src/foundry/common/documents.mjs/baseMacro.d.ts
- src/foundry/common/packages.mjs/packageAuthorData.d.ts
- src/foundry/foundry.js/canvasDocumentMixin.d.ts
- src/foundry/foundry.js/clientDocumentMixin.d.ts
- src/foundry/foundry.js/clientDocuments/activeEffect.d.ts
- src/foundry/foundry.js/clientDocuments/folder.d.ts
- src/foundry/foundry.js/collections/entityCollections/macros.d.ts
- src/foundry/foundry.js/config.d.ts
- src/types/helperTypes.ts
- test-d/foundry/common/abstract/document.mjs.test-d.ts
- test-d/foundry/common/documents.mjs/baseItem.test-d.ts
> Add configuration for _source

- src/foundry/foundry.js/roll.d.ts
- src/foundry/foundry.js/rollTerm.d.ts
- test-d/foundry/foundry.js/roll.test-d.ts
I'm not sure about all the `private` stuff, but this way is it as close to the source as possible.
I added the example from the docs as test. This does not test very much, but it is a start.
Closes #817
> Roll → v0.8.6

- src/foundry/common/constants.mjs.d.ts
closes #759
closes #760
closes #761
closes #762
> Add several Constants

- src/foundry/foundry.js/application.d.ts
- src/foundry/foundry.js/applications/compendium.d.ts
- src/foundry/foundry.js/applications/eula.d.ts
- src/foundry/foundry.js/applications/filePicker.d.ts
- src/foundry/foundry.js/applications/formApplication.d.ts
- src/foundry/foundry.js/applications/formApplications/baseEntitySheet.d.ts
- src/foundry/foundry.js/applications/formApplications/baseEntitySheets/permissionControl.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheet.d.ts
- src/foundry/foundry.js/applications/formApplications/moduleManagement.d.ts
- src/foundry/foundry.js/applications/formApplications/userConfig.d.ts
- src/foundry/foundry.js/applications/installPackage.d.ts
- src/foundry/foundry.js/applications/notifications.d.ts
- src/foundry/foundry.js/applications/sidebarTab.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectory.d.ts
- src/foundry/foundry.js/entity.d.ts
- test-d/foundry/foundry.js/application.test-d.ts
- test-d/foundry/foundry.js/documentSheet.test-d.ts
- test-d/foundry/foundry.js/draggable.test-d.ts
- test-d/foundry/foundry.js/formApplication.test-d.ts
> Application, FormApplication, DocumentSheet → v0.8.x

- src/foundry/common/documents.mjs/baseAmbientLight.d.ts
- src/foundry/common/documents.mjs/baseWall.d.ts
- src/foundry/foundry.js/applications/basePlaceableHUD.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObject.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/ambientLight.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/ambientSound.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/drawing.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/measuredTemplate.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/note.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/tile.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/token.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/wall.d.ts
- test-d/foundry/foundry.js/pixi/containers/placeableObject.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/placeableObjects/wall.test-d.ts
- test-d/foundry/foundry.js/pixi/shaders/containers/placeableObjects/tile.test-d.ts
> PlaceableObject → 0.8.x

- src/foundry/foundry.js/clientDocuments/actor.d.ts
Fixes #433
Only does things that are public, not deprecated, and not an override.
> Add methods and getters to Actor

- src/foundry/common/data/data.mjs/index.d.ts
- src/foundry/common/data/data.mjs/measuredTemplateData.d.ts
- src/foundry/common/documents.mjs/baseMeasuredTemplate.d.ts
- src/foundry/foundry.js/clientDocuments/canvasDocuments/measuredTemplateDocument.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/measuredTemplate.d.ts
- src/foundry/index.d.ts
- test-d/foundry/common/data/data.mjs/measuredTemplateData.test-d.ts
- test-d/foundry/common/documents.mjs/baseMeasuredTemplate.test-d.ts
- test-d/foundry/foundry.js/clientDocuments/canvasDocuments/measuredTemplateDocument.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/placeableObjects/measuredTemplate.test-d.ts
Resolves #484
Resolves #633 
Resolves #668 
Resolves #669
> MeasuredTemplate, BaseMeasuredTemplate, MeasuredTemplateData, MeasuredTemplateDocument -> v0.8.6

- src/foundry/foundry.js/applications/formApplications/activeEffectConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/activeEffectConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/index.d.ts
- src/foundry/foundry.js/applications/formApplications/index.d.ts
- test-d/foundry/foundry.js/applications/formApplications/activeEffectConfig.test-d.ts
- test-d/foundry/foundry.js/applications/formApplications/documentSheets/activeEffectConfig.test-d.ts
Resolves #712 
~~We need to move this class to applications/formApplications/documentSheets once #880 is merged.~~ Done.
> Update ActiveEffectConfig to 0.8.7

- src/foundry/foundry.js/applications/formApplication.d.ts
- test-d/foundry/foundry.js/applications/formApplications/documentSheets/itemSheet.test-d.ts
- test-d/foundry/foundry.js/applications/formApplications/documentSheets/userConfig.test-d.ts
Resolves #886 
I guess this is the right place to solve this issue, but if anyone has another opinion on this, feel free to contradict :-)
> Require the first parameter of FormApplication

- src/foundry/common/data/data.mjs/combatantData.d.ts
- src/foundry/common/data/data.mjs/index.d.ts
- test-d/foundry/common/data/data.mjs/combatantData.test-d.ts
> CombatantData

- src/foundry/common/data/data.mjs/tokenData.d.ts
- src/foundry/common/documents.mjs/baseDrawing.d.ts
- src/foundry/common/documents.mjs/basePlaylist.d.ts
- src/foundry/common/documents.mjs/basePlaylistSound.d.ts
- src/foundry/foundry.js/applications/formApplications/avConfig.d.ts
- src/foundry/foundry.js/formDataExtended.d.ts
- src/foundry/foundry.js/rollTerms/diceTerm.d.ts
Closes #895
Closes #896
Closes #898
Closes #899
> Update TokenData, DiceTerm, FormDataExtended, AVConfig for 0.8.8

- src/foundry/common/data/data.mjs/combatantData.d.ts
- src/foundry/common/documents.mjs/baseCombatant.d.ts
- src/foundry/foundry.js/clientDocuments/combatant.d.ts
- src/foundry/foundry.js/config.d.ts
- src/foundry/index.d.ts
- test-d/foundry/common/documents.mjs/baseCombatant.test-d.ts
- test-d/foundry/foundry.js/clientDocuments/combatant.test-d.ts
> Combatant, BaseCombatant

- src/foundry/common/abstract/document.mjs.d.ts
- src/foundry/common/data/data.mjs/tokenData.d.ts
- src/foundry/common/documents.mjs/baseToken.d.ts
- src/foundry/foundry.js/clientDocuments/actor.d.ts
- src/foundry/foundry.js/clientDocuments/canvasDocuments/tokenDocument.d.ts
- src/foundry/foundry.js/config.d.ts
- src/foundry/foundry.js/globals.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObject.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/token.d.ts
- src/foundry/index.d.ts
- test-d/foundry/foundry.js/clientDocuments/canvasDocuments/tokenDocument.test-d.ts
- test-d/foundry/foundry.js/clientDocuments/combatant.test-d.ts
- test-d/foundry/foundry.js/globals.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/placeableObjects/token.test-d.ts
Changes on `Combatant` has been made only to fix the build. `Combatant` should be addressed in another PR.
Resolves #486 
Resolves #642 
Resolves #688
> Token, BaseToken, TokenDocument → v0.8.6

- src/foundry/common/utils/helpers.mjs.d.ts
- test-d/foundry/common/utils/helpers.mjs.test-d.ts
See https://discord.com/channels/732325252788387980/803646399014109205/859023599527264256
> Merge arrays as arrays and not as records

- src/foundry/common/data/data.mjs/chatMessageData.d.ts
- src/foundry/common/data/data.mjs/chatSpeakerData.d.ts
- src/foundry/common/data/data.mjs/index.d.ts
- src/foundry/common/documents.mjs/baseChatMessage.d.ts
- src/foundry/foundry.js/clientDocuments/chatMessage.d.ts
- test-d/foundry/common/data/data.mjs/chatMessageData.test-d.ts
- test-d/foundry/common/documents.mjs/baseChatMessage.test-d.ts
- test-d/foundry/foundry.js/clientDocuments/chatMessage.test-d.ts
- test-d/foundry/foundry.js/collections/documentCollections/worldCollections/messages.test-d.ts
Resolves #646 
Resolves #645 
Resolves #623 
Resolves #448
> ChatSpeakerData, ChatMessageData, BaseChatMessage, ChatMessage → 0.8.8

- src/foundry/foundry.js/applications/filePicker.d.ts
as per https://foundryvtt.com/api/FilePicker.html
> filepicker can take a callback in the options

- src/foundry/common/data/data.mjs/drawingData.d.ts
- src/foundry/common/data/data.mjs/index.d.ts
- src/foundry/common/documents.mjs/baseDrawing.d.ts
- src/foundry/foundry.js/applications/formApplications/drawingConfig.d.ts
- src/foundry/foundry.js/canvasDocumentMixin.d.ts
- src/foundry/foundry.js/clientDocuments/canvasDocuments/drawingDocument.d.ts
- src/foundry/foundry.js/clientDocuments/canvasDocuments/measuredTemplateDocument.d.ts
- src/foundry/foundry.js/config.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObject.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/drawing.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/measuredTemplate.d.ts
- src/foundry/index.d.ts
- test-d/foundry/common/data/data.mjs/drawingData.test-d.ts
- test-d/foundry/common/documents.mjs/baseDrawing.test-d.ts
- test-d/foundry/foundry.js/clientDocuments/canvasDocuments/drawingDocument.test-d.ts
- test-d/foundry/foundry.js/clientDocuments/canvasDocuments/measuredTemplateDocument.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/placeableObjects/drawing.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/placeableObjects/measuredTemplate.test-d.ts
Resolves #480 
Resolves #626 
Resolves #657 
Resolves #658
> Drawing → 0.8.8

- src/foundry/foundry.js/textureUtils.d.ts
- test-d/foundry/foundry.js/textureUtils.test-d.ts
Resolves #804 
Resolves #805 
Resolves #806
> Update texture utils

- src/foundry/common/abstract/document.mjs.d.ts
- src/foundry/common/data/data.mjs/index.d.ts
- src/foundry/common/data/data.mjs/journalEntryData.d.ts
- src/foundry/common/data/data.mjs/settingData.d.ts
- src/foundry/common/documents.mjs/baseSetting.d.ts
- src/foundry/foundry.js/clientDocuments/actor.d.ts
- src/foundry/foundry.js/clientDocuments/chatMessage.d.ts
- src/foundry/foundry.js/clientDocuments/setting.d.ts
- test-d/foundry/common/data/data.mjs/settingData.test-d.ts
- test-d/foundry/common/documents.mjs/baseSetting.test-d.ts
- test-d/foundry/foundry.js/clientDocuments/setting.test-d.ts
- test-d/foundry/foundry.js/collections/documentCollections/worldCollections/worldSettings.test-d.ts
Closes #639
Closes #679
Closes #680
> 0.8.x/setting

- src/foundry/foundry.js/canvas.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/scenes.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/users.d.ts
- src/foundry/foundry.js/game.d.ts
- test-d/foundry/foundry.js/collections/documentCollections/worldCollections/scenes.test-d.ts
First part of `StoredDocument` for the very basic things:
- `game.user`
- `game.scenes.active`
- `game.scenes.current`
- `game.scenes.viewed`
- `game.users.current`
- `canvas.scene`
> Apply StoredDocument to game.scenes, game.user and canvas.scene

- src/foundry/foundry.js/canvas.d.ts
- src/foundry/foundry.js/canvasAnimation.d.ts
- src/foundry/foundry.js/perceptionManager.d.ts
- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/drawingsLayer.d.ts
- src/foundry/index.d.ts
- test-d/foundry/foundry.js/canvas.test-d.ts
- test-d/foundry/foundry.js/canvasAnimation.test-d.ts
- test-d/foundry/foundry.js/perceptionManager.test-d.ts
Resolves #725 
Resolves #459 
Resolves #347
> Canvas → 0.8.8

- src/foundry/foundry.js/applications/playerList.d.ts
> PlayerList → 0.8.8

- src/foundry/foundry.js/pixi/blendModes.d.ts
> BLEND_MODES → 0.8.8

- src/foundry/foundry.js/searchFilter.d.ts
- test-d/foundry/foundry.js/searchFilter.test-d.ts
> SearchFilter → 0.8.8

- src/foundry/foundry.js/pixi/graphics/resizeHandle.d.ts
> Update ResizeHandle to 0.8.8

- src/foundry/foundry.js/userTargets.d.ts
- test-d/foundry/foundry.js/clientDocuments/user.test-d.ts
- test-d/foundry/foundry.js/userTargets.test-d.ts
> UserTargets → 0.8.8

- src/foundry/foundry.js/applications/pause.d.ts
> Pause → 0.8.8

- src/foundry/foundry.js/pixi/containers/ruler.d.ts
- test-d/foundry/foundry.js/pixi/containers/ruler.test-d.ts
> Ruler → 0.8.8

- src/foundry/foundry.js/pixi/containers/baseGrid.d.ts
- src/foundry/foundry.js/pixi/containers/baseGrids/hexagonalGrid.d.ts
- src/foundry/foundry.js/pixi/containers/baseGrids/squareGrid.d.ts
- src/foundry/foundry.js/pixi/containers/canvasLayers/gridLayer.d.ts
> Basegrid, HexagonalGrid, SquareGrid → 0.8.8

- src/foundry/foundry.js/pixi/shaders/abstractBaseShader.d.ts
- src/foundry/foundry.js/pixi/shaders/abstractBaseShaders/standardColorationShaders/chromaColorationShader.d.ts
- src/foundry/foundry.js/pixi/shaders/abstractBaseShaders/standardColorationShaders/emanationColorationShader.d.ts
- src/foundry/foundry.js/pixi/shaders/abstractBaseShaders/standardColorationShaders/energyFieldColorationShader.d.ts
- src/foundry/foundry.js/pixi/shaders/abstractBaseShaders/standardColorationShaders/fogColorationShader.d.ts
- src/foundry/foundry.js/pixi/shaders/abstractBaseShaders/standardColorationShaders/hexaDomeColorationShader.d.ts
- src/foundry/foundry.js/pixi/shaders/abstractBaseShaders/standardColorationShaders/lightDomeColorationShader.d.ts
- src/foundry/foundry.js/pixi/shaders/abstractBaseShaders/standardColorationShaders/pulseColorationShader.d.ts
- src/foundry/foundry.js/pixi/shaders/abstractBaseShaders/standardColorationShaders/torchColorationShader.d.ts
- src/foundry/foundry.js/pixi/shaders/abstractBaseShaders/standardColorationShaders/waveColorationShader.d.ts
- test-d/foundry/foundry.js/pixi/shaders/abstractBaseShader.test-d.ts
Resolves #737 
Resolves #735 
Resolves #734 
Resolves #732 
Resolves #730
Resolves #729 
Resolves #728 
Resolves #727 
Resolves #488 
I think that #736, #733 and #731 can be closed too as I could not detect any differences.
> Various Shaders → 0.8.8

- src/foundry/foundry.js/keyboardManager.d.ts
- test-d/foundry/foundry.js/keyboardManager.test-d.ts
> KeyboardManager → 0.8.8

- src/foundry/foundry.js/clientDocuments/canvasDocuments/ambientLightDocument.d.ts
Almost everything was already done
Resolves #615
> AmbientLightDocument → 0.8.8

- src/foundry/index.d.ts
> Remove import for non exiting actorTokenHelpers

- src/foundry/foundry.js/pixi/containers/baseGrids/index.d.ts
- src/foundry/foundry.js/pixi/containers/canvasLayers/index.d.ts
- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/index.d.ts
- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/mapLayers/index.d.ts
- src/foundry/foundry.js/pixi/containers/index.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/index.d.ts
- src/foundry/foundry.js/pixi/filters/index.d.ts
- src/foundry/foundry.js/pixi/graphics/index.d.ts
- src/foundry/foundry.js/pixi/index.d.ts
- src/foundry/foundry.js/pixi/polygons/index.d.ts
- src/foundry/foundry.js/pixi/polygons/sourcePolygon.d.ts
- src/foundry/foundry.js/pixi/rectangles/index.d.ts
- src/foundry/foundry.js/pixi/shaders/abstractBaseShaders/index.d.ts
- src/foundry/foundry.js/pixi/shaders/abstractBaseShaders/standardColorationShaders/index.d.ts
- src/foundry/foundry.js/pixi/shaders/abstractBaseShaders/standardIlluminationShaders/index.d.ts
- src/foundry/foundry.js/pixi/shaders/index.d.ts
- src/foundry/foundry.js/pixi/texts/index.d.ts
- src/foundry/index.d.ts
- test-d/foundry/foundry.js/pixi/polygons/sourcePolygon.test-d.ts
Closes #681
Also restructures the way the PIXI related classes are imported. It's now hierarchical with `index.d.ts` files.
> 0.8.x/source polygon

- src/foundry/foundry.js/audioContainer.d.ts
- src/foundry/foundry.js/audioHelper.d.ts
- src/foundry/foundry.js/clientSettings.d.ts
- src/foundry/foundry.js/sound.d.ts
- src/foundry/index.d.ts
- test-d/foundry/foundry.js/audioContainer.test-d.ts
- test-d/foundry/foundry.js/audioHelper.test-d.ts
- test-d/foundry/foundry.js/sound.test-d.ts
Closes #317
Closes #889
Closes #747
Closes #748 (`Audio` doesn't actually exist, so nothing to do here)
> 0.8.x/audio

- src/foundry/common/data/data.mjs/chatMessageData.d.ts
- test-d/foundry/common/data/data.mjs/chatMessageData.test-d.ts
> Allow anything with an id as whisper constr arg

- src/foundry/common/abstract/backend.mjs.d.ts
- src/foundry/common/data/data.mjs/fogExplorationData.d.ts
- src/foundry/common/data/data.mjs/index.d.ts
- src/foundry/common/documents.mjs/baseFogExploration.d.ts
- src/foundry/foundry.js/clientDocuments/fogExploration.d.ts
- test-d/foundry/common/data/data.mjs/fogExplorationData.test-d.ts
- test-d/foundry/common/documents.mjs/baseFogExploration.test-d.ts
- test-d/foundry/foundry.js/clientDocuments/fogExploration.test-d.ts
- test-d/foundry/foundry.js/collections/documentCollections/worldCollections/fogExplorations.test-d.ts
Resolves #662 
Resolves #661 
Resolves #628
> FogExploration → 0.8.8

- README.md
That way we have at least some link to the npm package listing.
> Add an npm badge for latest tag

- src/foundry/foundry.js/applications/formApplications/gridConfig.d.ts
> Update GridConfig to 0.8.9

- src/foundry/foundry.js/applications/sidebar.d.ts
> Update Sidebar to 0.8.9

- src/foundry/foundry.js/applications/formApplications/folderConfig.d.ts
> Update FolderConfig to 0.8.9

- src/foundry/foundry.js/clientDocuments/actor.d.ts
- test-d/foundry/foundry.js/clientDocuments/actor.test-d.ts
> Fix invalid return type of Actor.getActiveTokens()

- src/foundry/foundry.js/clientDocuments/user.d.ts
- test-d/foundry/foundry.js/clientDocuments/user.test-d.ts
> Fix a ToDo on User and add missing User.{charname,color,border}

- src/foundry/foundry.js/applications/formApplications/documentSheets/actorSheet.d.ts
- test-d/foundry/foundry.js/applications/formApplications/documentSheets/actorSheet.test-d.ts
> Fix ActorSheet.token

- src/foundry/foundry.js/config.d.ts
- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/wallsLayer.d.ts
- src/types/helperTypes.d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayer.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/drawingsLayer.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/lightingLayer.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/mapLayer.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/notesLayer.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/soundsLayer.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/templateLayer.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/tokenLayer.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/wallsLayer.test-d.ts
Adds an interface and some helper types for configuring
CONFIG.<Placeable>.objectClass similar to DocumentClassConfig
Update tests
> Add PlaceableObjectClassConfig

- src/foundry/foundry.js/applications/mainMenu.d.ts
- test-d/foundry/foundry.js/applications/mainMenu.test-d.ts
> Update MainMenu to 0.8.9

- src/foundry/foundry.js/applications/sidebarTabs/combatTracker.d.ts
- test-d/foundry/foundry.js/applications/sidebarTabs/combatTracker.test-d.ts
> CombatTracker → v0.8.9

- src/foundry/foundry.js/application.d.ts
- src/foundry/foundry.js/applications/basePlaceableHUD.d.ts
- src/foundry/foundry.js/applications/basePlaceableHUDs/drawingHUD.d.ts
- src/foundry/foundry.js/applications/basePlaceableHUDs/tileHUD.d.ts
- src/foundry/foundry.js/applications/basePlaceableHUDs/tokenHUD.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObject.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/ambientLight.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/ambientSound.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/drawing.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/note.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/tile.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/wall.d.ts
- test-d/foundry/foundry.js/applications/basePlaceableHUD.test-d.ts
- test-d/foundry/foundry.js/applications/basePlaceableHUD/drawingHUD.test-d.ts
- test-d/foundry/foundry.js/applications/basePlaceableHUD/tileHUD.test-d.ts
- test-d/foundry/foundry.js/applications/basePlaceableHUD/tokenHUD.test-d.ts
- test-d/foundry/foundry.js/pixi/shaders/containers/placeableObjects/tile.test-d.ts
Resolves #386 
Resolves #720 
Resolves #718 
Resolves #717
> Update HUDs to v0.8.9

- src/foundry/common/constants.mjs.d.ts
- src/foundry/foundry.js/globalVariables.d.ts
> update constants and global variables

- src/foundry/foundry.js/pixi/filters/abstractBaseMaskFilter.d.ts
- src/foundry/foundry.js/pixi/filters/abstractBaseMaskFilters/index.d.ts
- src/foundry/foundry.js/pixi/filters/abstractBaseMaskFilters/inverseOcclusionMaskFilter.d.ts
- src/foundry/foundry.js/pixi/filters/index.d.ts
- test-d/foundry/foundry.js/pixi/filter/abstractBaseMaskFilter.test-d.ts
- test-d/foundry/foundry.js/pixi/filter/abstractBaseMaskFilters/inverseOcclusionMaskFilter.test-d.ts
> Add InverseOcclusionMaskFilter

- src/foundry/foundry.js/specialEffect.d.ts
- src/foundry/foundry.js/specialEffects/autumnLeavesWeatherEffect.d.ts
- src/foundry/foundry.js/specialEffects/index.d.ts
- src/foundry/foundry.js/specialEffects/rainWeatherEffect.d.ts
- src/foundry/foundry.js/specialEffects/snowWeatherEffect.d.ts
- src/foundry/index.d.ts
Mostly, things have just been reordered.
Closes #739
Closes #740
Closes #741
Closes #742
> Update special effects

- src/foundry/foundry.js/applications/chatPopout.d.ts
- test-d/foundry/foundry.js/applications/chatPopout.test-d.ts
> Update ChatPopout to 0.8.9

- src/foundry/foundry.js/chatBubbles.d.ts
- test-d/foundry/foundry.js/chatBubbles.test-d.ts
Resolves #551 
(I guess someone already did, but some `@internal` were missing)
> Update ChatBubbles to 0.8.9

- src/foundry/foundry.js/applications/formApplications/wallConfig.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/wall.d.ts
- test-d/foundry/foundry.js/pixi/containers/placeableObjects/wall.test-d.ts
> Update Wall to 0.8.9

- src/foundry/foundry.js/applications/formApplications/documentSheet.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/permissionControl.d.ts
> Update PermissionControl for 0.8.9

- src/foundry/foundry.js/applications/formApplications/documentSheets/rollTableConfig.d.ts
> Update RollTableConfig for 0.8.x

- src/foundry/foundry.js/applications/formApplications/drawingConfig.d.ts
> Update DrawingConfig for 0.8.x

- src/foundry/foundry.js/applications/sceneNavigation.d.ts
> Update SceneNavigation for 0.8.x

- src/foundry/foundry.js/applications/formApplications/documentSheets/sceneConfig.d.ts
> Update SceneConfig for 0.8.x

- src/foundry/foundry.js/applications/formApplications/entitySheetConfig.d.ts
- src/foundry/foundry.js/config.d.ts
> Update EntitySheetConfig for 0.8.x

- src/foundry/foundry.js/applications/formApplications/combatTrackerConfig.d.ts
- src/foundry/foundry.js/clientDocuments/canvasDocuments/tokenDocument.d.ts
> Update CombatTrackerConfig for 0.8.x

- src/foundry/foundry.js/applications/formApplications/wallConfig.d.ts
> Update WallConfig for 0.8.x

- src/foundry/foundry.js/applications/formApplications/settingsConfig.d.ts
- src/foundry/foundry.js/clientSettings.d.ts
> Update SettingsConfig for 0.8.x

- src/foundry/foundry.js/applications/formApplications/worldConfig.d.ts
> Update WorldConfig for 0.8.x

- src/foundry/foundry.js/applications/formApplication.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/activeEffectConfig.d.ts
- src/foundry/foundry.js/applications/formApplications/tokenConfig.d.ts
- src/foundry/foundry.js/clientDocuments/canvasDocuments/tokenDocument.d.ts
- test-d/foundry/foundry.js/applications/formApplications/documentSheets/activeEffectConfig.test-d.ts
> 0.8.x/token config

- src/foundry/common/abstract/document.mjs.d.ts
> Update DocumentModificationOptions/DocumentModificationContext for 0.8.x

- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/actorDirectory.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/itemDirectory.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/journalDirectory.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/macroDirectory.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/sceneDirectory.d.ts
Closes #416 
Closes #420 
Closes #421 
Closes #422 
Closes #424
> 0.8.x/sidebar directories

- src/foundry/common/abstract/backend.mjs.d.ts
- src/foundry/foundry.js/collections/documentCollections/compendiumCollection.d.ts
- test-d/foundry/foundry.js/collections/documentCollections/compendiumCollection.test-d.ts
> Update CompendiumCollection for 0.8.9

- src/foundry/foundry.js/pointSource.d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/sightLayer.test-d.ts
- test-d/foundry/foundry.js/pointSource.test-d.ts
> Update PointSource for 0.8.x

- src/foundry/foundry.js/applications/cameraViews.d.ts
- src/foundry/foundry.js/cameraPopoutAppWrapper.d.ts
> 0.8.x/camera

- src/foundry/common/abstract/backend.mjs.d.ts
- src/foundry/common/abstract/document.mjs.d.ts
- src/foundry/common/types.mjs.d.ts
- src/foundry/foundry.js/clientDatabaseBackend.d.ts
- src/foundry/foundry.js/config.d.ts
- src/foundry/index.d.ts
Closes #647
This doesn't type everything in the best way yet but it's pretty difficult, given how low level this is and how bad foundry documents all of this stuff (the socket requests etc.). I think it's good enough for now as basically nobody uses this directly.
If somebody wants to take the time to actually type all the possible socket requests / responses correctly, feel free to do so but I think it's not worth it.
> Add ClientDatabaseBackend for 0.8.x

- src/foundry/common/constants.mjs.d.ts
> Update constants.mjs for V9.235

- src/foundry/foundry.js/clientDocumentMixin.d.ts
- test-d/foundry/foundry.js/clientDocuments/macro.test-d.ts
> Update ClientDocumentMixin to v9

- src/foundry/foundry.js/canvasDocumentMixin.d.ts
> Update CanvasDocumentMixin to v9.235

- src/foundry/common/abstract/document.mjs.d.ts
> Update Document to v9.236

- src/foundry/common/data/fields.mjs.d.ts
> Update fields.mjs to v9.235

- src/foundry/foundry.js/config.d.ts
- test-d/foundry/foundry.js/canvas.test-d.ts
> Update config to v9.235

- src/foundry/common/constants.mjs.d.ts
> Update constants.mjs to v9.236

- src/foundry/foundry.js/clientSettings.d.ts
- src/foundry/foundry.js/game.d.ts
- src/foundry/foundry.js/newUserExperience.d.ts
- src/foundry/index.d.ts
Closes #1456.
Closes #1457.
Closes #1458.
> Add NewUserExperience

- src/foundry/foundry.js/roll.d.ts
- src/foundry/foundry.js/rollTerm.d.ts
- src/foundry/foundry.js/rollTerms/diceTerm.d.ts
- src/foundry/foundry.js/rollTerms/mathTerm.d.ts
- src/foundry/foundry.js/rollTerms/parentheticalTerm.d.ts
- src/foundry/foundry.js/rollTerms/poolTerm.d.ts
- src/foundry/foundry.js/rollTerms/stringTerm.d.ts
Closes #1001 
Closes #1302
Closes #1303
Closes #1304
Closes #1305
Closes #1306
Closes #1307
Closes #1308
> Update Dice classes to Foundry v9.233

- src/foundry/foundry.js/canvas.d.ts
- src/foundry/foundry.js/config.d.ts
- src/foundry/foundry.js/hooks.d.ts
- src/foundry/foundry.js/pixi/containers/cachedContainer.d.ts
- src/foundry/foundry.js/pixi/containers/cachedContainers/index.d.ts
- src/foundry/foundry.js/pixi/containers/cachedContainers/primaryCanvasGroup.d.ts
- src/foundry/foundry.js/pixi/containers/canvasLayers/index.d.ts
- src/foundry/foundry.js/pixi/containers/canvasLayers/weatherLayer.d.ts
- src/foundry/foundry.js/pixi/containers/effectsCanvasGroup.d.ts
- src/foundry/foundry.js/pixi/containers/index.d.ts
- src/foundry/foundry.js/pixi/containers/interfaceCanvasGroup.d.ts
- test-d/foundry/foundry.js/canvas.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/weatherLayer.test-d.ts
> Update Canvas, rename EffectsLayer to WeatherLayer

- src/foundry/common/utils/primitives.mjs.d.ts
Also added a bunch of documentation that had been missing for some
reason.
Closes #993
> Update primitives for V9

- src/foundry/foundry.js/gamepadManager.d.ts
- src/foundry/foundry.js/keyboardManager.d.ts
> Update GamepadManager and KeyboardManager for V9.238

- src/foundry/common/data/data.mjs/cardData.d.ts
- src/foundry/common/data/data.mjs/cardsData.d.ts
> Update CardData and CardsData for V9.238

- src/foundry/common/utils/helpers.mjs.d.ts
- test-d/foundry/common/utils/helpers.mjs.test-d.ts
> Update helpers.mjs for V9.238

- src/foundry/common/data/data.mjs/cardData.d.ts
- src/foundry/common/data/data.mjs/cardsData.d.ts
- src/foundry/common/documents.mjs/baseCard.d.ts
- src/foundry/common/documents.mjs/baseCards.d.ts
- src/foundry/common/documents.mjs/index.d.ts
- src/foundry/foundry.js/config.d.ts
- test-d/foundry/common/data/data.mjs/cardData.test-d.ts
- test-d/foundry/common/documents.mjs/baseActor.test-d.ts
- test-d/foundry/common/documents.mjs/baseCard.test-d.ts
- test-d/foundry/common/documents.mjs/baseCards.test-d.ts
- test-d/foundry/common/documents.mjs/baseItem.test-d.ts
> Add BaseCard and BaseCards

- src/foundry/common/data/data.mjs/combatData.d.ts
- src/foundry/common/data/data.mjs/combatantData.d.ts
- src/foundry/common/data/data.mjs/effectChangeData.d.ts
- src/foundry/common/data/data.mjs/folderData.d.ts
- src/foundry/common/data/data.mjs/macroData.d.ts
- src/foundry/common/data/data.mjs/measuredTemplateData.d.ts
- src/foundry/common/data/data.mjs/noteData.d.ts
- src/foundry/common/data/data.mjs/playlistData.d.ts
- src/foundry/common/data/data.mjs/playlistSoundData.d.ts
- src/foundry/common/data/data.mjs/sceneData.d.ts
- src/foundry/common/data/data.mjs/userData.d.ts
- src/foundry/common/data/data.mjs/wallData.d.ts
- test-d/foundry/common/data/data.mjs/wallData.test-d.ts
Closes #1431
Closes #1432
Closes #1433
Closes #983
Closes #987
Closes #1237
Closes #1241
Closes #1242
Closes #1244
Closes #1245
Closes #1246
Closes #1247
> Update remaining data classes to v9.238

- src/foundry/common/data/data.mjs/adventureData.d.ts
- src/foundry/common/data/data.mjs/index.d.ts
> Add AdventureData

- src/foundry/common/documents.mjs/baseAdventure.d.ts
- src/foundry/common/documents.mjs/index.d.ts
- src/foundry/foundry.js/config.d.ts
> Add BaseAdventure

- src/foundry/common/constants.mjs.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/cardsDirectory.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/index.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/cardStacks.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/index.d.ts
- src/foundry/foundry.js/config.d.ts
- src/foundry/foundry.js/game.d.ts
> Add CardStacks and CardsDirectory

- src/foundry/foundry.js/game.d.ts
> Update Game.Data to v9.238

- src/foundry/foundry.js/imageHelper.d.ts
> Update ImageHelper to v9.238

- src/foundry/foundry.js/specialEffect.d.ts
> Update SpecialEffect to v9.238

- src/foundry/foundry.js/audioContainer.d.ts
> Update AudioContainer to v9.238

- src/foundry/foundry.js/pixi/texts/preciseText.d.ts
> Update PreciseText to v9.238

- src/foundry/foundry.js/hooks.d.ts
- test-d/foundry/foundry.js/custom-error-hooks.d.ts
- test-d/foundry/foundry.js/hooks.test-d.ts
> Update hooks to v9.238

- src/foundry/common/data/data.mjs/userData.d.ts
> Update UserData for V9.242

- src/foundry/foundry.js/applications/sidebarTabs/chatLog.d.ts
- src/foundry/foundry.js/clientDocuments/chatMessage.d.ts
- src/foundry/foundry.js/clientDocuments/rollTable.d.ts
- src/foundry/foundry.js/clientSettings.d.ts
- src/foundry/foundry.js/config.d.ts
- src/foundry/foundry.js/roll.d.ts
- test-d/foundry/foundry.js/clientDocuments/chatMessage.test-d.ts
- test-d/foundry/foundry.js/clientSettings.test-d.ts
> Properly type CONFIG.Dice.rollModes

- src/foundry/foundry.js/imageHelper.d.ts
> Update ImageHelper for V9.242

- src/foundry/foundry.js/clientKeybindings.d.ts
> Update ClientKeybindings to v9.242

- src/foundry/foundry.js/keyboardManager.d.ts
> Update KeyboardManager for V9.242

- src/foundry/foundry.js/hooks.d.ts
> Add i18nInit hook event for v9.242

- src/foundry/foundry.js/clientDocuments/cards.d.ts
- test-d/foundry/foundry.js/clientDocuments/cards.test-d.ts
> Update Cards to V9.242

- src/foundry/foundry.js/roll.d.ts
- test-d/foundry/foundry.js/roll.test-d.ts
> Update Roll to V9.242

- src/foundry/common/documents.mjs/baseCombatant.d.ts
- src/foundry/foundry.js/clientDocuments/combat.d.ts
- src/foundry/foundry.js/clientDocuments/combatant.d.ts
Closes #1453
Closes #1009
Closes #1008
> Update BaseCombatant, Combatant, and Combat for V9.242

- src/foundry/foundry.js/clientDocuments/actor.d.ts
- test-d/foundry/foundry.js/clientDocuments/actor.test-d.ts
> Improve itemTypes

- src/foundry/foundry.js/roll.d.ts
- test-d/foundry/foundry.js/roll.test-d.ts
> Improve Roll

- src/foundry/foundry.js/pixi/rectangles/normalizedRectangle.d.ts
> Update NormalizedRectangle to v9.242

- src/foundry/foundry.js/pixi/index.d.ts
- src/foundry/foundry.js/pixi/meshes/index.d.ts
- src/foundry/foundry.js/pixi/meshes/samplerMesh.d.ts
> Add SamplerMesh

- src/foundry/foundry.js/pixi/index.d.ts
- src/foundry/foundry.js/pixi/transforms/index.d.ts
- src/foundry/foundry.js/pixi/transforms/synchronizedTransform.d.ts
> Add SynchronizedTransform

- src/foundry/foundry.js/textureUtils.d.ts
- test-d/foundry/foundry.js/textureUtils.test-d.ts
> Update loadTexture to v9.242

- src/foundry/foundry.js/applications/sidebarTab.d.ts
> Update SidebarTab for v9.245

- src/foundry/foundry.js/applications/sidebarTabs/combatTracker.d.ts
- test-d/foundry/foundry.js/applications/sidebarTabs/combatTracker.test-d.ts
> Update CombatTracker for v9.245

- src/foundry/foundry.js/application.d.ts
- test-d/foundry/foundry.js/application.test-d.ts
> Allow setting height: 'auto' in the options passed to Application#render

- src/foundry/foundry.js/applications/formApplications/entitySheetConfig.d.ts
- src/foundry/foundry.js/avSettings.d.ts
- src/foundry/foundry.js/clientDocumentMixin.d.ts
- src/foundry/foundry.js/clientDocuments/user.d.ts
- src/foundry/foundry.js/collections/documentCollection.d.ts
- src/foundry/foundry.js/collections/documentCollections/compendiumCollection.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollection.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/actors.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/combatEncounters.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/fogExplorations.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/folders.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/items.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/journal.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/macros.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/messages.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/playlists.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/rollTables.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/scenes.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/users.d.ts
- src/foundry/foundry.js/collections/documentCollections/worldCollections/worldSettings.d.ts
- src/foundry/foundry.js/pixi/containers/ruler.d.ts
- test-d/foundry/foundry.js/collections/documentCollections/compendiumCollection.test-d.ts
- test-d/foundry/foundry.js/collections/documentCollections/worldCollections/combatEncounters.test-d.ts
- test-d/foundry/foundry.js/collections/documentCollections/worldCollections/fogExplorations.test-d.ts
- test-d/foundry/foundry.js/collections/documentCollections/worldCollections/folders.test-d.ts
- test-d/foundry/foundry.js/collections/documentCollections/worldCollections/messages.test-d.ts
- test-d/foundry/foundry.js/collections/documentCollections/worldCollections/users.test-d.ts
- test-d/foundry/foundry.js/collections/documentCollections/worldCollections/worldSettings.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/ruler.test-d.ts
Closes #1325
Closes #1324
Closes #1323
Closes #1322
Closes #1321
Closes #1320
Closes #1319
Closes #1318
Closes #1317
Closes #1316
Closes #1315
Closes #1313
Closes #1312
Closes #1004
Closes #1003
Closes #1002
> V9.249/collections

- src/foundry/foundry.js/game.d.ts
> Fix Game#PackageData#packs

- src/foundry/common/utils/semaphore.mjs.d.ts
> Update Semaphore for v9

- src/foundry/common/utils/http.mjs.d.ts
- src/foundry/common/utils/module.mjs.d.ts
- test-d/foundry/common/utils/http.mjs.test-d.ts
> Add http.mjs for v9

- src/foundry/common/types.mjs.d.ts
- src/foundry/foundry.js/applications/formApplications/settingsConfig.d.ts
- src/foundry/foundry.js/clientSettings.d.ts
- src/foundry/foundry.js/gamepadManager.d.ts
> Update types.mjs and ClientSettings for V9

- src/foundry/foundry.js/clientDocuments/actor.d.ts
> Update Actor for V9

- src/foundry/foundry.js/clientDocuments/item.d.ts
> Update Item for V9

- src/foundry/foundry.js/clientDocuments/folder.d.ts
> Update Folder to v9

- src/foundry/foundry.js/clientDocuments/canvasDocuments/tokenDocument.d.ts
> Update TokenDocument for v9

- src/foundry/foundry.js/clientDocuments/macro.d.ts
> Update Macro for v9

- src/foundry/foundry.js/clientDocuments/activeEffect.d.ts
> Update ActiveEffect for v9

- src/foundry/foundry.js/clientDocuments/playlistSound.d.ts
> Update PlaylistSound for v9

- src/foundry/foundry.js/clientDocumentMixin.d.ts
- src/foundry/foundry.js/clientDocuments/scene.d.ts
> Update Scene for v9

- src/foundry/foundry.js/clientDocuments/rollTable.d.ts
> Update RollTyble for v9

- src/foundry/foundry.js/clientDocuments/prototypeToken.d.ts
> Update PrototypeTokenDocument for v9

- src/foundry/foundry.js/clientDocuments/user.d.ts
> Update User for v9

- src/foundry/foundry.js/pixi/containers/placeableObject.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/ambientSound.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/drawing.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/measuredTemplate.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/note.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/tile.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/token.d.ts
> Update PlaceableObject for v9

- src/foundry/foundry.js/pixi/containers/baseGrid.d.ts
- src/foundry/foundry.js/pixi/containers/baseGrids/hexagonalGrid.d.ts
- src/foundry/foundry.js/pixi/containers/baseGrids/squareGrid.d.ts
- src/foundry/foundry.js/pixi/containers/canvasLayers/gridLayer.d.ts
Closes #1434
Closes #1435
Closes #1459
Closes #1460
> Update grid related classes to v9

- src/foundry/foundry.js/applications/formApplications/documentSheets/actorSheet.d.ts
> Update ActorSheet to v9.255

- src/foundry/foundry.js/handlebarsHelpers.d.ts
> Update HandlebarsHelpers for v9

- src/foundry/foundry.js/mouseInteractionManager.d.ts
> Update MouseInteractionManager for v9

- src/foundry/foundry.js/perceptionManager.d.ts
- test-d/foundry/foundry.js/perceptionManager.test-d.ts
> Update PerceptionManager for v9

- src/foundry/foundry.js/pixi/containers/placeableObjects/drawing.d.ts
> Update Drawing for v9

- src/foundry/foundry.js/pixi/containers/placeableObjects/ambientLight.d.ts
- test-d/foundry/foundry.js/pixi/containers/placeableObjects/ambientLight.test-d.ts
> Update AmbientLight for v9

- src/foundry/foundry.js/pixi/containers/placeableObjects/note.d.ts
> Update Note for v9

- src/foundry/foundry.js/pixi/containers/placeableObjects/ambientSound.d.ts
- test-d/foundry/foundry.js/pixi/containers/placeableObjects/ambientSound.test-d.ts
> Update AmbientSound for v9

- src/foundry/foundry.js/applications/dialog.d.ts
- src/foundry/foundry.js/clientDocumentMixin.d.ts
- src/foundry/foundry.js/clientDocuments/cards.d.ts
- src/foundry/foundry.js/clientDocuments/folder.d.ts
- src/foundry/foundry.js/collections/documentCollections/compendiumCollection.d.ts
- test-d/foundry/foundry.js/applications/dialog.test-d.ts
> Update Dialog for v9

- src/foundry/foundry.js/applications/sidebar.d.ts
> Update SideBar for v9

- src/foundry/foundry.js/clientDocuments/playlist.d.ts
> Update Playlist for v9

- src/foundry/foundry.js/applications/formApplications/worldConfig.d.ts
> Update WorldConfig for v9

- src/foundry/foundry.js/applications/sceneNavigation.d.ts
> Update SceneNavigation for v9

- src/foundry/common/types.mjs.d.ts
- src/foundry/foundry.js/applications/formApplications/avConfig.d.ts
- test-d/foundry/foundry.js/applications/formApplications/avConfig.test-d.ts
> Update AVConfig for v9

- src/foundry/foundry.js/pixi/containers/placeableObjects/tile.d.ts
> Update Tile for v9

- src/foundry/foundry.js/pixi/containers/index.d.ts
- src/foundry/foundry.js/pixi/containers/objectHUD.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/measuredTemplate.d.ts
- src/types/utils.d.ts
- test-d/types/utils.test-d.ts
Closes #1061
This builds on top of #1675 and should only be merged afterwards.
> Update MeasuredTemplate for v9

- src/foundry/foundry.js/pixi/containers/index.d.ts
- src/foundry/foundry.js/pixi/containers/objectHUD.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/token.d.ts
- src/types/utils.d.ts
- test-d/types/utils.test-d.ts
Closes #1063
This builds upon #1675 and should only be merged afterwards
> Update Token for v9

- src/foundry/foundry.js/pixi/containers/placeableObjects/wall.d.ts
- test-d/foundry/foundry.js/pixi/containers/placeableObjects/wall.test-d.ts
> Update Wall for v9

- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/journalDirectory.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/macroDirectory.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/playlistDirectory.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/rollTableDirectory.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/sceneDirectory.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectory.d.ts
- src/foundry/foundry.js/hooks.d.ts
> Update SidebarDirectory for v9

- src/foundry/foundry.js/applications/hotbar.d.ts
> Update Hotbar for v9

- src/foundry/foundry.js/applications/cameraViews.d.ts
> Update CameraViews for v9

- src/foundry/foundry.js/applications/basePlaceableHUDs/tokenHUD.d.ts
> Update TokenHUD for v9

- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayer.d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayer.test-d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/mapLayer.test-d.ts
> Update PlaceablesLayer to v9.255

- src/foundry/foundry.js/pixi/containers/controlIcon.d.ts
> Update ControlIcon for v9

- src/foundry/foundry.js/applications/invitationLinks.d.ts
- src/foundry/foundry.js/game.d.ts
> Update InvitationLinks for v9

- src/foundry/foundry.js/applications/index.d.ts
- src/foundry/foundry.js/applications/supportDetails.d.ts
> Add SupportDetails and SupportReportData for v9

- src/foundry/foundry.js/contextMenu.d.ts
- test-d/foundry/foundry.js/contextMenu.test-d.ts
> Update ContextMenu for v9

- src/foundry/foundry.js/applications/formApplications/tokenConfig.d.ts
> Update TokenConfig for v9

- src/foundry/foundry.js/applications/formApplications/wallConfig.d.ts
> Update WallConfig for v9

- src/foundry/foundry.js/applications/filePicker.d.ts
- src/foundry/foundry.js/applications/formApplication.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/playlistConfig.d.ts
> Update FilePicker for v9

- src/foundry/foundry.js/applications/formApplications/combatTrackerConfig.d.ts
> Update CombatTrackerConfig for v9

- src/foundry/foundry.js/applications/formApplications/documentSheets/combatantConfig.d.ts
> Update CombatantConfig for v9

- src/foundry/foundry.js/applications/formApplications/documentSheets/folderConfig.d.ts
> Update FolderConfig for v9

- src/foundry/foundry.js/applications/formApplications/gridConfig.d.ts
> Update GridConfig for v9

- src/foundry/foundry.js/applications/formApplications/imagePopout.d.ts
> Update ImagePopout for v9

- src/foundry/foundry.js/applications/formApplications/documentSheets/itemSheet.d.ts
> Update ItemSheet for v9

- src/foundry/foundry.js/applications/formApplications/documentSheets/journalSheet.d.ts
- test-d/foundry/foundry.js/applications/formApplications/documentSheets/journalSheet.test-d.ts
> Update JournalSheet for v9

- src/foundry/foundry.js/applications/formApplications/documentSheets/macroConfig.d.ts
> Update MacroConfig for v9

- src/foundry/foundry.js/applications/formApplications/documentSheets/measuredTemplateConfig.d.ts
> Update MeasuredTemplateConfig for v9

- src/foundry/foundry.js/applications/formApplications/documentSheets/permissionControl.d.ts
> Update PermissionControl for v9

- src/foundry/foundry.js/applications/formApplications/documentSheets/playlistConfig.d.ts
> Update PlaylistConfig for v9

- src/foundry/foundry.js/applications/formApplications/documentSheets/rollTableConfig.d.ts
> Update RollTableConfig for v9

- src/foundry/foundry.js/applications/formApplication.d.ts
- src/foundry/foundry.js/applications/formApplications/documentSheets/sceneConfig.d.ts
> Update SceneConfig for v9

- src/foundry/foundry.js/applications/formApplications/drawingConfig.d.ts
> Update DrawingConfig for v9

- src/foundry/foundry.js/applications/formApplications/documentSheets/tileConfig.d.ts
> Update TileConfig for v9

- src/foundry/foundry.js/applications/chatPopout.d.ts
> Update ChatPopout for v9

- src/foundry/foundry.js/applications/formApplications/settingsConfig.d.ts
> Update SettingsConfig for v9

- src/foundry/foundry.js/applications/controlsReference.d.ts
> Update ControlsReference for v9

- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/actorDirectory.d.ts
> Update ActorDirectory for v9

- src/foundry/foundry.js/applications/sidebarTabs/compendiumDirectory.d.ts
> Update CompendiumDirectory for v9

- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/journalDirectory.d.ts
> Update JournalDirectory for v9

- src/foundry/foundry.js/application.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/playlistDirectory.d.ts
- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectory.d.ts
> Update PlaylistDirectory for v9

- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/macroDirectory.d.ts
> Update MacroDirectory for v9

- src/foundry/foundry.js/applications/sidebarTabs/sidebarDirectories/sceneDirectory.d.ts
> Update SceneDirectory for v9

- src/foundry/foundry.js/applications/formApplications/moduleManagement.d.ts
> Update ModuleManagement for v9

- src/foundry/foundry.js/clientDocuments/chatMessage.d.ts
- test-d/foundry/foundry.js/clientDocuments/chatMessage.test-d.ts
> Update ChatMessage for v9

- src/foundry/foundry.js/applications/sidebarTabs/chatLog.d.ts
> Update ChatLog for v9

- src/foundry/foundry.js/applications/sidebarTabs/settings.d.ts
> Update Settings for v9

- src/foundry/foundry.js/applications/compendium.d.ts
> Update Compendium for v9

- src/foundry/foundry.js/clientDocuments/cards.d.ts
- src/foundry/foundry.js/clientDocuments/folder.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/tile.d.ts
- src/foundry/foundry.js/pixi/containers/placeableObjects/token.d.ts
- src/foundry/foundry.js/rollTerms/poolTerm.d.ts
Closes #1747
Closes #1746
Closes #1745
Closes #1744
Closes #1743
> Update classes that have already been updated for v9 to v9.266

- src/foundry/foundry.js/pixi/filters/abstractFilter.d.ts
- src/foundry/foundry.js/pixi/filters/index.d.ts
> Add AbstractFilter for v9

- src/foundry/foundry.js/pixi/filters/abstractFilter.d.ts
- src/foundry/foundry.js/pixi/filters/abstractFilters/glowFilter.d.ts
- src/foundry/foundry.js/pixi/filters/abstractFilters/index.d.ts
- src/foundry/foundry.js/pixi/filters/index.d.ts
> Add GlowFilter for v9

- src/foundry/foundry.js/pixi/filters/abstractFilters/fogColorFilter.d.ts
- src/foundry/foundry.js/pixi/filters/abstractFilters/index.d.ts
- src/foundry/foundry.js/pixi/filters/index.d.ts
> Add FogColorFilter for v9

- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/soundsLayer.d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/soundsLayer.test-d.ts
> Update SoundsLayer to v9.266

- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/notesLayer.d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/notesLayer.test-d.ts
> Update NotesLayer to v9.266

- src/foundry/foundry.js/pixi/containers/canvasLayers/controlsLayer.d.ts
- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/wallsLayer.d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/wallsLayer.test-d.ts
> Update WallsLayer to v9.266

- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/tokenLayer.d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/tokenLayer.test-d.ts
> Update TokenLayer to v9.266

- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/mapLayer.d.ts
- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/mapLayers/foregroundLayer.d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/mapLayers/foregroundLayer.test-d.ts
> Update ForegroundLayer to v9.266

- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/mapLayers/backgroundLayer.d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/mapLayers/backgroundLayer.test-d.ts
> Update BackgroundLayer to v9.266

- src/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/lightingLayer.d.ts
- test-d/foundry/foundry.js/pixi/containers/canvasLayers/placeablesLayers/lightingLayer.test-d.ts
> Update LightingLayer to v9.266

- package-lock.json
- package.json
- src/types/augments/index.d.ts
- src/types/augments/pixiGraphicsSmooth.d.ts
- src/types/augments/pixiLegacyGraphics.d.ts
- tsconfig.json
> Augment PIXI with LegacyGraphics

- src/foundry/common/data/data.mjs/effectChangeData.d.ts
> Fix active effect change "mode" type

- src/foundry/client/ui/tabs.d.ts
> Update tabs.d.ts to v10.276

- src/foundry/client/ui/filepicker.d.ts
> Update filepicker.d.ts to v10.276

- src/foundry/client/ui/notifications.d.ts
- test-d/foundry/client/ui/notifications.test-d.ts
> Update notifications.d.ts to v10.276

- src/foundry/client/apps/app.d.ts
- src/foundry/client/core/hooks.d.ts
> Update Application to v10.276

- package-lock.json
- package.json
- src/foundry/client/apps/app.d.ts
- src/foundry/client/apps/form.d.ts
- src/foundry/client/apps/sidebar/apps/world-config.d.ts
- src/foundry/client/core/hooks.d.ts
Depends on #1857 
Closes #1859
> Update FormApplication to v10.276

- src/foundry/client/ui/forms.d.ts
> Update forms.d.ts to v10.276

- src/foundry/client/game.d.ts
- src/types/config.d.ts
- src/types/helperTypes.d.ts
- test-d/foundry/client/game.test-d.ts
Attempts to implement #2103. Draft stage right now, will refactor for less monkey patching feeling later.
> Implement "Allow Arbitrary additions to ModuleData"

- src/foundry/client/av/settings.d.ts
> Updated AVSettings to v10.277

- src/foundry/client/audio/audio.d.ts
- src/foundry/client/audio/container.d.ts
- src/foundry/client/audio/sound.d.ts
- test-d/foundry/client/audio/audio.test-d.ts
> Update src/foundry/client/audio to v10.277

- package-lock.json
- package.json
- src/foundry/client/core/hooks.d.ts
- src/foundry/client/head.d.ts
- src/foundry/client/ui/index.d.ts
- src/foundry/client/ui/prosemirror.d.ts
- src/foundry/index.d.ts
- src/foundry/prosemirror/content-link-plugin.d.ts
- src/foundry/prosemirror/dirty-plugin.d.ts
- src/foundry/prosemirror/dropdown.d.ts
- src/foundry/prosemirror/extensions.d.ts
- src/foundry/prosemirror/image-plugin.d.ts
- src/foundry/prosemirror/index.d.ts
- src/foundry/prosemirror/input-rules.d.ts
- src/foundry/prosemirror/keymaps.d.ts
- src/foundry/prosemirror/menu.d.ts
- src/foundry/prosemirror/plugin.d.ts
- src/foundry/prosemirror/prosemirror.d.ts
- src/foundry/prosemirror/schema.d.ts
- src/foundry/prosemirror/string-serializer.d.ts
- src/foundry/prosemirror/util.d.ts
- test-d/foundry/client/ui/prosemirror.test-d.ts
- test-d/foundry/prosemirror/prosemirror.test-d.ts
This should be everything for prosemirror, ignoring #2088 as the one external bit that touches it, closes #2092.
> Add prosemirror dependacies, types for client/ui/prosemirror.mjs, and foundry/scripts/prosemirror.js

- package-lock.json
- package.json
- src/foundry/client/core/hooks.d.ts
- src/foundry/client/head.d.ts
- src/foundry/client/ui/editor.d.ts
- src/foundry/client/ui/index.d.ts
- src/foundry/client/ui/prosemirror.d.ts
- src/foundry/index.d.ts
- src/foundry/prosemirror/content-link-plugin.d.ts
- src/foundry/prosemirror/dirty-plugin.d.ts
- src/foundry/prosemirror/dropdown.d.ts
- src/foundry/prosemirror/extensions.d.ts
- src/foundry/prosemirror/image-plugin.d.ts
- src/foundry/prosemirror/index.d.ts
- src/foundry/prosemirror/input-rules.d.ts
- src/foundry/prosemirror/keymaps.d.ts
- src/foundry/prosemirror/menu.d.ts
- src/foundry/prosemirror/plugin.d.ts
- src/foundry/prosemirror/prosemirror.d.ts
- src/foundry/prosemirror/schema.d.ts
- src/foundry/prosemirror/string-serializer.d.ts
- src/foundry/prosemirror/util.d.ts
- test-d/foundry/client/ui/prosemirror.test-d.ts
- test-d/foundry/prosemirror/prosemirror.test-d.ts
Fixes #2088, now depends on #2104.
> Update editor.d.ts to v10.276

- src/foundry/client/dice/dice/die.d.ts
- src/foundry/client/dice/roll.d.ts
- src/foundry/client/dice/terms/operator.d.ts
- src/foundry/client/dice/terms/parenthetical.d.ts
- src/foundry/client/dice/terms/pool.d.ts
Fixes #1978, fixes #1979, fixes #1980, fixes #1981, fixes #1992.
> Update client/dice to v10.277

- src/foundry/client/core/document-index.d.ts
- src/foundry/client/core/hooks.d.ts
- src/foundry/client/core/image.d.ts
- src/foundry/client/core/index.d.ts
- src/foundry/client/core/keybindings.d.ts
- src/foundry/client/core/keyboard.d.ts
- src/foundry/client/core/mouse.d.ts
- src/foundry/client/core/settings.d.ts
- src/foundry/client/core/sorting.d.ts
- src/foundry/client/core/time.d.ts
- src/foundry/client/core/tooltip.d.ts
- src/foundry/client/core/tour.d.ts
- src/foundry/client/core/tours.d.ts
- src/foundry/client/core/workers.d.ts
- src/foundry/client/game.d.ts
Skips just resources/app/client/core/packages.js (#1924) as I don't have
enough brain cells for this right now.
Resolves #1919, resolves #1920, resolves #1921, resolves #1922,
resolves #1923, resolves #1925, resolves #1926, resolves #1927.
Now also resolves #1983.
> Update most of src/foundry/client/core to v10.277

- .github/dependabot.yml
- package-lock.json
- package.json
- src/foundry/client/pixi/layers/effects/effect.d.ts
- src/foundry/client/pixi/layers/effects/leaves.d.ts
- src/foundry/client/pixi/layers/effects/rain.d.ts
- src/foundry/client/pixi/layers/effects/snow.d.ts
- src/types/augments/index.d.ts
- src/types/augments/pixiParticleEmitter.d.ts
> Update pixi-particles to @pixi/particle-emitter v5.0.7

- package-lock.json
- package.json
> Update @pixi/graphics-smooth to v0.0.30

- package-lock.json
- package.json
- src/types/augments/socket.io-client.d.ts
> Update socket.io-client to v4.5.1

- src/foundry/client/apps/sidebar/tabs/settings.d.ts
- test-d/foundry/client/apps/sidebar/tabs/settings.test-d.ts
> Fix FrameViewer constructor signature

- package-lock.json
- package.json
- src/foundry/client/config.d.ts
- src/types/augments/tinyMCE.d.ts
> Update tinymce to v6.1.0

- .github/dependabot.yml
- index.d.ts
- package-lock.json
- package.json
> Add showdown

- src/foundry/clipper/clipper.d.ts
- src/foundry/clipper/index.d.ts
- src/foundry/index.d.ts
> Add clipper

- src/foundry/client/core/tooltip.d.ts
> Update TooltipManager for V10.279

- src/foundry/client/apps/i18n.d.ts
- src/foundry/client/core/tour.d.ts
- src/foundry/client/core/tours.d.ts
- src/foundry/common/utils/color.mjs.d.ts
> Update Tour and Tours for V10.279

- src/foundry/client/core/settings.d.ts
- src/foundry/common/types.mjs.d.ts
Added new property requiresReload
> SettingConfig default property is now mandatory

- src/foundry/client/apps/av/cameras.d.ts
> Update CameraViews to v10.287

- src/foundry/client/apps/forms/cards-config.d.ts
> Update CardsConfig for v10.288

- package-lock.json
- package.json
- src/foundry/client/core/video.d.ts
> Update VideoHelper to v10.287

- src/foundry/client/core/workers.d.ts
> Update workers.d.ts to v10.287

- src/foundry/client/head.d.ts
- src/types/augments/index.d.ts
- src/types/augments/pixiGraphics.d.ts
- test-d/foundry/client/core/time.test-d.ts
- test-d/foundry/client/head.test-d.ts
> Update head.d.ts to v10.288

- src/foundry/client/apps/placeables/note-config.d.ts
> Update NoteConfig type to foundry V10

- src/foundry/client/data/documents/wall.d.ts
> Update Wall to v10.291

- src/foundry/client/pixi/core/shapes/ray.d.ts
> Deleted the typing for SightRay

- src/foundry/client/pixi/core/shapes/source-polygon.d.ts
> Updated PointSourcePolygon to v10.291.

- src/foundry/client/data/documents/ambient-sound.d.ts
> Updated AmbientSoundDocument for v10.291.

- src/foundry/client/pixi/core/containers/base-canvas-group.d.ts
- src/foundry/client/pixi/core/containers/index.d.ts
> Added BaseCanvasMixin for v10.291.

- src/foundry/client/data/documents/ambient-light.d.ts
> Updated AmbientLightDocument for v10.291.

- src/foundry/client/data/documents/card.d.ts
> Updated Card for v10.291.

- src/foundry/client/pixi/sources/light-source.d.ts
> Updated LightSource to v10.291.

- src/foundry/client/pixi/core/loader.d.ts
> Updated TextureLoader for v10.291.

- src/foundry/client/data/documents/macro.d.ts
> Updated Macro for v10.291.

- src/foundry/client/data/documents/measured-template.d.ts
> Updated MeasuredTemplateDocument for v10.291.

- src/foundry/client/data/documents/note.d.ts
> Updated NoteDocument for v10.291.

- src/foundry/client/data/documents/table-result.d.ts
> Updated TableResult for v10.291.

- src/foundry/client/data/documents/playlist-sound.d.ts
> Updated PlaylistSound for v10.291.

- src/foundry/client/data/documents/table.d.ts
> Updated RollTable for v10.291.

- src/foundry/client/data/documents/tile.d.ts
> Updated TileDocument for v10.291.

- src/foundry/client/data/documents/chat-message.d.ts
> Updated ChatMessage for v10.291.

- src/foundry/client/data/documents/combat.d.ts
- src/foundry/client/data/documents/note.d.ts
> Updated Combat for v10.291.

- src/foundry/client/data/documents/playlist.d.ts
> Updated Playlist for v10.291.

- src/foundry/client/data/documents/setting.d.ts
> Updated Setting for v10.291.

- src/foundry/client/data/documents/token.d.ts
- test-d/foundry/client/data/documents/token.test-d.ts
> Updated TokenDocument to v10.291.

- src/foundry/client/core/tour.d.ts
I think a bunch of this work had already been done? Just a few missing pieces
> 2275 - Tour

- src/foundry/client/apps/forms/measure-template.d.ts
> MeasuredTemplateConfig

- src/foundry/client/apps/forms/macro-config.d.ts
> Macro Config

- src/foundry/client/apps/forms/index.d.ts
- src/foundry/client/apps/forms/ownership.d.ts
Only touching this one file + the necessary imports.
Closes #1876
> PermissionControl => DocumentOwnershipConfig

- src/foundry/client/apps/forms/roll-table-config.d.ts
> RollTableConfig

- src/foundry/client/apps/forms/scene-config.d.ts
> Scene Config

- src/foundry/client/apps/hud/chatbubble.d.ts
Double check how I handled ChatBubbleOptions; I think from other examples adding it as an interface was correct?
Closes #1880
> ChatBubbles

- src/foundry/client/core/keyboard.d.ts
> KeyboardManager

- src/foundry/client/core/tooltip.d.ts
> TooltipManager

- src/foundry/client/apps/sidebar/apps/keybindings-config.d.ts
- src/foundry/client/apps/sidebar/package-configuration.d.ts
> KeybindingsConfig

- src/foundry/client/ui/context.d.ts
> ContextMenu

- src/foundry/client/apps/sidebar/tab-base.d.ts
- tsconfig.json
> SidebarTab

- src/foundry/client/apps/forms/user-config.d.ts
- src/foundry/client/apps/placeables/token-hud.d.ts
- src/foundry/client/config.d.ts
- src/foundry/client/dice/dice/coin.d.ts
- src/foundry/client/pixi/layers/controls/ruler.d.ts
- src/foundry/client/ui/context.d.ts
- src/foundry/common/data/data.mjs/noteData.d.ts
- src/foundry/common/data/data.mjs/sceneData.d.ts
I happened to notice a few defaults were wrong.
> Fix some default values

- src/foundry/client/dice/roll.d.mts
- src/foundry/client/dice/term.d.mts
- src/foundry/client/dice/terms/pool.d.mts
Handful of updates to the classes in the `dice` folder
> Dice updates

- src/foundry/client/av/settings.d.mts
Closes #2123 (No signature changes), #2204
> Updated AVSettings

- src/foundry/client/tours/setup-tour.d.mts
> Tours to v11

- src/foundry/client/audio/audio.d.mts
- src/foundry/client/audio/container.d.mts
Minor updates to bring the Audio classes to v11
> Audio to v11

- README.md
Updated description & the tsconfig to match current setup of main.
> Proposed Updates to README

- src/foundry/client/config.d.mts
- tests/foundry/client/config.test-d.ts
Some ts-expect-error on account of the missing DataModel setup, but that can be handled later. The previous v10 updates to this somehow missed out on the DetectionMode stuff.
> CONFIG updates

- src/foundry/client/apps/sidebar/apps/compendium.d.mts
- src/foundry/client/apps/sidebar/directory-tab-mixin.d.mts
- src/foundry/client/apps/sidebar/document-directory.d.mts
Not 100% sure about everything here. Main open questions:
- Some things look like they're marked `protected` in types that don't seem to have that annotation in the source
- Does `private` in source -> `@internal` in types? 
- Not entirely sure about the `Metadata` at the beginning.
> first try at compendium sidebar

- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/ISSUE_TEMPLATE/update_class.yaml
- .github/ISSUE_TEMPLATE/update_for_v12.yaml
- .github/ISSUE_TEMPLATE/wrong_type.yaml
Adjusted the issue templates ahead of the commencement of v12 work
> Updated issue templates

- tests/foundry/client/data/documents/journal-entry-page.test-d.ts
I took example in the existing tests, I think this is good, but do not hesitate to tell me if I got it wrong :)
> Created Journal Entry Page test file

- src/foundry/client/apps/sidebar/apps/module-management.d.mts
- src/foundry/client/core/index.d.mts
- src/foundry/client/core/issues.d.mts
- src/foundry/client/game.d.mts
Solves #2582 .
No tests because nothing but plain signatures. I can add some if someone points out where they are needed.
> client.core.issues

- src/foundry/prosemirror/index.d.mts
- src/foundry/prosemirror/schema.d.mts
- src/foundry/prosemirror/schema/attribute-capture.d.mts
- src/foundry/prosemirror/schema/core.d.mts
- src/foundry/prosemirror/schema/image-link-node.d.mts
- src/foundry/prosemirror/schema/image-node.d.mts
- src/foundry/prosemirror/schema/index.d.mts
- src/foundry/prosemirror/schema/link-mark.d.mts
- src/foundry/prosemirror/schema/lists.d.mts
- src/foundry/prosemirror/schema/marks.d.mts
- src/foundry/prosemirror/schema/other.d.mts
- src/foundry/prosemirror/schema/schema-definition.d.mts
- src/foundry/prosemirror/schema/secret-node.d.mts
- src/foundry/prosemirror/schema/tables.d.mts
- src/foundry/prosemirror/schema/utils.d.mts
Necessary for the Prosemirror move into common
> Prosemirror updates into v12/main

- src/foundry/common/utils/collection.d.mts
No implementation changes, just matching generic letter to source (T -> V)
This resolves #2601
> Match generic letter to source v12

- src/foundry/common/utils/geometry.d.mts
- tests/foundry/common/utils/geometry.mjs.test-d.ts
added:
And appropriate tests.
Solves #2603
> Geometry to v12

- src/foundry/common/utils/logging.d.mts
- tests/foundry/common/utils/logging.mjs.test-d.ts
>  Update logging.mjs #2608

- src/foundry/client-esm/canvas/edges/edge.d.mts
- src/foundry/client-esm/canvas/sources/base-effect-source.d.mts
- src/foundry/client-esm/canvas/sources/base-light-source.d.mts
- src/foundry/client-esm/canvas/sources/global-light-source.d.mts
- src/foundry/client-esm/canvas/sources/point-darkness-source.d.mts
- src/foundry/client-esm/canvas/sources/point-effect-source.d.mts
- src/foundry/client-esm/canvas/sources/point-light-source.d.mts
- src/foundry/client-esm/canvas/sources/point-movement-source.d.mts
- src/foundry/client-esm/canvas/sources/point-sound-source.d.mts
- src/foundry/client-esm/canvas/sources/point-vision-source.d.mts
- src/foundry/client-esm/canvas/sources/rendered-effect-source.d.mts
- src/foundry/client/data/abstract/directory-collection-mixin.d.mts
- src/foundry/client/data/abstract/world-collection.d.mts
- src/foundry/client/data/collections/compendium-collection.d.mts
- src/foundry/client/data/collections/compendium-packs.d.mts
- tests/foundry/client-esm/canvas/sources/base-effect-source.mjs.test-d.ts
- tests/foundry/client-esm/canvas/sources/base-light-source.mjs.test-d.ts
- tests/foundry/client-esm/canvas/sources/global-light-source.mjs.test-d.ts
- tests/foundry/client-esm/canvas/sources/point-darkness-sources.mjs.test-d.ts
- tests/foundry/client-esm/canvas/sources/point-light-source.mjs.test-d.ts
- tests/foundry/client-esm/canvas/sources/point-movement-source.mjs.test-d.ts
- tests/foundry/client-esm/canvas/sources/point-sound-source.mjs.test-d.ts
- tests/foundry/client-esm/canvas/sources/point-vision-source.mjs.test-d.ts
- tests/foundry/client-esm/canvas/sources/rendered-effect-source.mjs.test-d.ts
> Client-esm/Canvas/Sources

- src/foundry/common/utils/http.d.mts
>  Update http.mjs #2605

- src/foundry/common/abstract/data.d.mts
- src/foundry/common/data/validation-failure.d.mts
- tests/foundry/common/data/validation-failure.mjs.test-d.ts
Resolved issues with the constructor, added in the `cause` handling.
Closes #2644
> Fixed DataModelValidationError

- src/foundry/client-esm/helpers/_types.d.mts
- src/foundry/client-esm/helpers/compendium-art.d.mts
- tests/foundry/client-esm/helpers/compendium-art.test-d.ts
> client-esm.helpers.compendium-art

- src/foundry/common/abstract/module.d.mts
- src/foundry/common/abstract/socket.d.mts
> Added DocumentSocketResponse

- src/foundry/client/data/documents/macro.d.mts
- tests/foundry/client/data/documents/macro.test-d.ts
- tests/foundry/common/documents/macro.test-d.ts
Closes #2658 while also working in bug fixes for the return value
> Macro execute fixes

- src/foundry/client-esm/applications/_types.d.mts
- src/foundry/client-esm/applications/api/application.d.mts
- tests/foundry/client-esm/applications/api/application.test-d.ts
Added missing interface contents
> Updated appv2 _types

- src/foundry/client-esm/applications/_types.d.mts
- src/foundry/client-esm/applications/api/application.d.mts
- src/foundry/client-esm/applications/api/document-sheet.d.mts
- src/foundry/client-esm/applications/api/handlebars-application.d.mts
- src/foundry/client-esm/applications/apps/compendium-art-config.d.mts
- src/foundry/client-esm/applications/apps/permission-config.d.mts
- src/foundry/client-esm/applications/dice/roll-resolver.d.mts
- src/foundry/client-esm/applications/sheets/ambient-light-config.d.mts
- src/foundry/client-esm/applications/sheets/ambient-sound-config.d.mts
- src/foundry/client-esm/applications/sheets/region-behavior-config.d.mts
- src/foundry/client-esm/applications/sheets/region-config.d.mts
- src/foundry/client-esm/applications/sheets/user-config.d.mts
- src/foundry/client-esm/applications/ui/region-legend.d.mts
- src/foundry/client/config.d.mts
- src/types/helperTypes.d.mts
- tests/foundry/client-esm/applications/api/handlebars-application.test-d.ts
I would still consider my ApplicationV2 auditing work incomplete but this at least gets it closer.
> Audit Application V2 Again

- src/types/helperTypes.d.mts
- src/types/utils.d.mts
I wrote pretty exhaustive documentation so that's what should be focused on, I think.
> Add More Helper Types

- src/foundry/client/ui/dragdrop.d.mts
Closes #2678.
Not much to update here. Replaced a few Partials with InexactPartials. Updates some function types and docs.
> Updates dragdrop.js

- src/foundry/client/data/documents/chat-message.d.mts
Updates ChatMessage to v12.
Since BaseChatMessage might result in a merge conflict here's a patch file for it.
[baseChatMessage.patch](https://github.com/user-attachments/files/16428427/baseChatMessage.patch)
> Updates client ChatMessage.

- src/foundry/client/data/documents/playlist-sound.d.mts
- src/foundry/client/data/documents/setting.d.mts
- src/foundry/client/data/documents/table.d.mts
- src/foundry/client/data/documents/tile.d.mts
- src/foundry/client/data/documents/user.d.mts
Closes #2721. Closes #2718 . Closes #2717 . Closes #2715
> Updates User, RollTable, Setting and PlaylistSound to v12

- src/foundry/client/data/documents/drawing.d.mts
- src/foundry/client/data/documents/fog-exploration.d.mts
- src/foundry/client/data/documents/folder.d.mts
- tests/foundry/client/data/documents/drawing.test-d.ts
- tests/foundry/client/data/documents/fog-exploration.test-d.ts
- tests/foundry/client/data/documents/folder.test-d.ts
Addresses  #2706, #2707, #2708
> Folder, FogExploration, and DrawingDocument

- src/foundry/client/data/documents/measured-template.d.mts
- src/foundry/client/data/documents/playlist.d.mts
- tests/foundry/client/data/documents/adventure.test-d.ts
- tests/foundry/client/data/documents/measured-template.test-d.ts
- tests/foundry/client/data/documents/playlist.test-d.ts
- tests/foundry/client/data/documents/user.test-d.ts
- tests/foundry/client/pixi/placeables/template.test-d.ts
> playlist, measured template

- src/foundry/client/ui/forms.d.mts
- src/foundry/client/ui/notifications.d.mts
- tests/foundry/client/ui/forms.test-d.ts
Addresses #2681 and also updated some JSDoc comments on client/ui/notifications.js to match v12
> Formdataextended

- src/foundry/client/core/document-index.d.mts
- src/foundry/client/core/issues.d.mts
- src/foundry/client/core/keybindings.d.mts
- src/foundry/client/core/keyboard.d.mts
- src/foundry/client/core/socket.d.mts
- src/foundry/common/types.d.mts
- src/foundry/common/utils/string-tree.d.mts
- src/foundry/common/utils/word-tree.d.mts
- tests/foundry/client/core/document-index.test-d.ts
- tests/foundry/client/core/issues.test-d.ts
- tests/foundry/client/core/keybindings.test-d.ts
- tests/foundry/client/core/keyboard.test-d.ts
- tests/foundry/client/core/socket.test-d.ts
- tests/foundry/common/utils/word-tree.mjs.test-d.ts
Addresses #2753, #2754, #2755, #2759, and #2751
> V12/client/core/keybindings, keyboard, issues, socket, documentindex

- src/foundry/client/ui/context.d.mts
- src/foundry/client/ui/filepicker.d.mts
- tests/foundry/client/ui/context.test-d.ts
- tests/foundry/client/ui/filepicker.test-d.ts
> ui/Filepicker and Dialog

- package.json
- src/foundry/client-esm/applications/forms/fields.d.mts
- src/foundry/client/data/documents/macro.d.mts
- src/foundry/client/ui/editor.d.mts
- src/foundry/common/abstract/document.d.mts
- Updates for 331
- Bugfix in TextEditor
> More type fixes

- src/foundry/common/grid/_module.d.mts
- src/foundry/common/grid/base.d.mts
- src/foundry/common/grid/grid-hex.d.mts
- src/foundry/common/grid/gridless.d.mts
- src/foundry/common/grid/hexagonal.d.mts
- src/foundry/common/grid/square.d.mts
> Migrates Grid to common for v12

- .eslintrc.cjs
- src/types/augments/tinyMCE.d.mts
- tests/foundry/client/ui/filepicker.test-d.ts
Should resolve remaining lint errors
> Remaining lint errors

- src/foundry/client-esm/applications/sheets/actor-sheet.d.mts
- src/foundry/client-esm/applications/sheets/item-sheet.d.mts
> ActorSheetV2 and ItemSheetV2

- src/foundry/common/abstract/data.d.mts
- src/foundry/common/data/data.d.mts
- src/foundry/common/documents/token.d.mts
> feat: update common/data/data.mjs to 331

- src/foundry/client/pixi/layers/base/interaction-layer.d.mts
- src/foundry/client/pixi/layers/base/placeables-layer.d.mts
All of these classes will be migrated to ESM in v13 but it right now looks to be mostly just a copy-paste so not too many worries.
> #2843 Base Layers

- src/foundry/client/pixi/core/containers/base-canvas-group.d.mts
- src/foundry/client/pixi/groups/effects.d.mts
- src/foundry/client/pixi/groups/environment.d.mts
- src/foundry/client/pixi/groups/hidden.d.mts
- src/foundry/client/pixi/groups/interface.d.mts
- src/foundry/client/pixi/groups/primary.d.mts
Another set of classes which are moving to ESM in v13 but otherwise do not seem to be receiving substantial changes
Closes #2844
> 2844 Canvas Groups

- package-lock.json
- package.json
- src/foundry/client/pixi/placeables/primary-canvas-objects/index.d.mts
- src/foundry/client/pixi/placeables/primary-canvas-objects/primary-canvas-object.d.mts
- src/foundry/client/pixi/placeables/primary-canvas-objects/primary-graphics.d.mts
- src/foundry/client/pixi/placeables/primary-canvas-objects/primary-occludable-object.d.mts
- src/foundry/client/pixi/placeables/primary-canvas-objects/primary-sprite-mesh.d.mts
- src/types/augments/pixi.d.mts
- tests/tsconfig.json
Did not perform deletions, pending updates to various dependent classes
Closes #2855
> Added new classes in `client/pixi/placeables/primary-canvas-objects`

- src/foundry/client-esm/client.d.mts
- src/foundry/client/data/documents/scene.d.mts
- src/foundry/common/data/fields.d.mts
- src/foundry/common/grid/base.d.mts
- src/foundry/common/grid/hexagonal.d.mts
> Update Scene to v12.331

- src/foundry/client/pixi/placeable.d.mts
> PlaceableObject to v12.331

- src/foundry/client/apps/i18n.d.mts
> Updated Localization to v12.331

- src/foundry/client/apps/form.d.mts
> Updated FormApplication, DocumentSheet to v12.331

- src/foundry/client/apps/app.d.mts
> Updated Application to v12.331

- src/foundry/client/core/packages.d.mts
> Updated ClientPackage to v12.331

- src/foundry/client/core/settings.d.mts
> Updated ClientSettings to v12.331

- src/foundry/client-esm/canvas/scene-manager.d.mts
> Implemented SceneManager

- src/foundry/client/pixi/core/loader.d.mts
- src/foundry/client/pixi/placeables/primary-canvas-objects/primary-sprite-mesh.d.mts
> TextureLoader to v12.331

- src/foundry/client/pixi/core/shapes/index.d.mts
- src/foundry/client/pixi/extensions/circle.d.mts
- src/foundry/client/pixi/extensions/graphics.d.mts
- src/foundry/client/pixi/extensions/index.d.mts
- src/foundry/client/pixi/extensions/observable-transform.d.mts
- src/foundry/client/pixi/extensions/polygon.d.mts
- src/foundry/client/pixi/extensions/rectangle.d.mts
- src/types/augments/pixi.d.mts
- tests/foundry/client/pixi/extensions/circle.test-d.ts
- tests/foundry/client/pixi/extensions/graphics.test-d.ts
> Updated PIXI extensions

- src/foundry/client/pixi/layers/masks/depth.d.mts
- src/foundry/client/pixi/layers/masks/occlusion.d.mts
- src/foundry/client/pixi/layers/masks/vision.d.mts
> Updated Masks

- src/foundry/client/pixi/core/containers/cached-container.d.mts
- src/foundry/client/pixi/groups/effects.d.mts
- src/foundry/client/pixi/layers/effects/darkness-effects.d.mts
- src/foundry/client/pixi/layers/effects/illumination-effects.d.mts
- src/foundry/client/pixi/layers/effects/index.d.mts
- src/foundry/client/pixi/layers/effects/visibility.d.mts
- src/foundry/client/pixi/layers/effects/weather-effects.d.mts
- src/foundry/client/pixi/layers/effects/weather/particles/effect.d.mts
> Effects Layers

- src/foundry/client/pixi/layers/grid/index.d.mts
- src/foundry/client/pixi/layers/grid/layer.d.mts
- src/foundry/client/pixi/layers/grid/mesh.d.mts
> Grid Layer

- src/foundry/common/abstract/data.d.mts
Minor updates, Kai already added LOCALIZATION_PREFIXES
Closes #2810
> DataModel to v12.331

- src/foundry/client/data/documents/scene.d.mts
- src/foundry/client/hooks.d.mts
- src/foundry/client/pixi/board.d.mts
- src/foundry/client/pixi/core/interaction/canvas-animation.d.mts
This is going to need updates after CONFIG is updated since lots of external functions assign properties to canvas, but this gets the actual class updates done. Note that a LOT of functions got deleted purely from their migration to pure private.
Closes #2872
> Updated Canvas to v12.331

- src/foundry/common/abstract/data.d.mts
- src/foundry/common/abstract/document.d.mts
- src/foundry/common/documents/actor-delta.d.mts
- src/foundry/common/documents/adventure.d.mts
- src/foundry/common/documents/fog-exploration.d.mts
- src/foundry/common/documents/playlist-sound.d.mts
- src/foundry/common/documents/playlist.d.mts
- src/foundry/common/documents/setting.d.mts
- src/foundry/common/documents/user.d.mts
Tackled a range of base document updates that require minimal tests (No DocumentTypeField)
Closes #2881 
Closes #2815 
Closes #2885
Closes #2825 
Closes #2826 
Closes #2828 
Closes #2830
> Document schema updates

- src/foundry/client/core/index.d.mts
- src/foundry/client/game.d.mts
- tests/foundry/client/game.test-d.ts
- Big reorganization by core software to improve the types for their docs site
- Many properties are no longer readonly (`writable: false` was mistakenly removed)
Closes #2928
> Updated Game to v12

- src/foundry/client/data/collections/actors.d.mts
- src/foundry/client/data/collections/compendium-collection.d.mts
- src/foundry/client/data/collections/compendium-folders.d.mts
- src/foundry/client/data/collections/folder.d.mts
- src/foundry/client/data/collections/journal.d.mts
- src/foundry/client/data/collections/playlists.d.mts
- src/foundry/client/data/collections/users.d.mts
> Document Collections

- src/foundry/client/data/documents/active-effect.d.mts
- src/foundry/client/data/documents/actor-delta.d.mts
- src/foundry/client/data/documents/actor.d.mts
- src/foundry/client/data/documents/adventure.d.mts
- src/foundry/client/data/documents/ambient-light.d.mts
- src/foundry/client/data/documents/ambient-sound.d.mts
- src/foundry/client/data/documents/card.d.mts
- src/foundry/client/data/documents/cards.d.mts
- src/foundry/client/data/documents/chat-message.d.mts
- src/foundry/client/data/documents/combat.d.mts
- src/foundry/client/data/documents/combatant.d.mts
- src/foundry/client/data/documents/drawing.d.mts
- src/foundry/client/data/documents/fog-exploration.d.mts
- src/foundry/client/data/documents/folder.d.mts
- src/foundry/client/data/documents/item.d.mts
- src/foundry/client/data/documents/journal-entry-page.d.mts
- src/foundry/client/data/documents/journal-entry.d.mts
- src/foundry/client/data/documents/macro.d.mts
- src/foundry/client/data/documents/measured-template.d.mts
- src/foundry/client/data/documents/note.d.mts
- src/foundry/client/data/documents/playlist-sound.d.mts
- src/foundry/client/data/documents/playlist.d.mts
- src/foundry/client/data/documents/scene.d.mts
- src/foundry/client/data/documents/setting.d.mts
- src/foundry/client/data/documents/table-result.d.mts
- src/foundry/client/data/documents/table.d.mts
- src/foundry/client/data/documents/tile.d.mts
- src/foundry/client/data/documents/token.d.mts
- src/foundry/client/data/documents/user.d.mts
- src/foundry/client/data/documents/wall.d.mts
Also made a few fixes & adjustments along the way
Closes #2941
> Added helpful aliases to all client document classes

- src/types/utils.d.mts
I messed up the `extends` and `=` parts of the `D` param
> Fix the broken fix

- package-lock.json
- src/foundry/client/apps/sidebar/document-directory.d.mts
Found a small bug that was causing an error downstream
> Deprecation + bugfix

- src/foundry/client/core/image.d.mts
update interface pattern and comments, find actual type for storage key
> Updates to ImageHelper (again)

- src/foundry/client-esm/applications/ui/region-legend.d.mts
> Add client-esm/applications/ui/region-legend

- src/foundry/common/abstract/backend.d.mts
- src/foundry/common/abstract/document.d.mts
- src/foundry/common/documents/measured-template.d.mts
- Correctness Update for _onCreateOperation
- Stylistic update for delete operations
> Updated Document Operations

- src/foundry/client/apps/dice/dice-config.d.mts
- src/foundry/client/apps/dice/index.d.mts
- src/foundry/client/apps/index.d.mts
- src/foundry/client/config.d.mts
- src/types/config.d.mts
> Add DiceConfig

- src/foundry/client-esm/canvas/tokens/ring-config.d.mts
- src/foundry/client-esm/canvas/tokens/ring-data.d.mts
- src/foundry/client-esm/canvas/tokens/ring.d.mts
- src/foundry/client/config.d.mts
- tests/foundry/client-esm/canvas/tokens/ring-data.test-d.ts
> Add `client-esm/canvas/tokens`

- src/types/augments/particles.d.mts
- src/types/augments/pixi.d.mts
- src/types/augments/smooth.d.mts
> Add literals and comments back to PIXI enum overrides

- src/foundry/client/pixi/placeables/primary-canvas-objects/primary-canvas-object.d.mts
- src/foundry/client/pixi/placeables/primary-canvas-objects/primary-graphics.d.mts
- src/foundry/client/pixi/placeables/primary-canvas-objects/primary-occludable-object.d.mts
- src/foundry/client/pixi/placeables/primary-canvas-objects/primary-sprite-mesh.d.mts
- tests/foundry/client/pixi/placeables/primary-canvas-objects/drawing-shape.test-d.ts
- tests/foundry/client/pixi/placeables/primary-canvas-objects/occludable-object.test-d.ts
- tests/foundry/client/pixi/placeables/primary-canvas-objects/primary-canvas-object.test-d.ts
- tests/foundry/client/pixi/placeables/primary-canvas-objects/primary-graphics.test-d.ts
- tests/foundry/client/pixi/placeables/primary-canvas-objects/primary-occludable-object.test-d.ts
- tests/foundry/client/pixi/placeables/primary-canvas-objects/primary-sprite-mesh.test-d.ts
- tests/foundry/client/pixi/placeables/primary-canvas-objects/tile-mesh.test-d.ts
- tests/foundry/client/pixi/placeables/primary-canvas-objects/token-mesh.test-d.ts
> Types and tests for `client/pixi/placeables/primary-canvas-objects/**`

- src/configuration/globals.d.mts
- src/foundry/client/pixi/core/loader.d.mts
- tests/foundry/client/pixi/core/loader.test-d.ts
> Types and tests for TextureLoader and associated global functions 

- src/foundry/client-esm/canvas/sources/base-effect-source.d.mts
- src/foundry/client/config.d.mts
- src/foundry/client/hooks.d.mts
- src/foundry/client/pixi/core/containers/base-canvas-group.d.mts
- src/foundry/client/pixi/core/containers/quadtree.d.mts
- src/foundry/client/pixi/core/interaction/canvas-animation.d.mts
- src/foundry/client/pixi/groups/effects.d.mts
- src/foundry/client/pixi/groups/environment.d.mts
- src/foundry/client/pixi/groups/hidden.d.mts
- src/foundry/client/pixi/groups/interface.d.mts
- src/foundry/client/pixi/groups/overlay.d.mts
- src/foundry/client/pixi/groups/primary.d.mts
- src/foundry/client/pixi/groups/rendered.d.mts
- src/foundry/client/pixi/layers/effects/visibility.d.mts
- src/foundry/client/pixi/placeables/primary-canvas-objects/primary-canvas-object.d.mts
- src/foundry/client/pixi/placeables/primary-canvas-objects/primary-sprite-mesh.d.mts
- tests/foundry/client/pixi/core/containers/base-canvas-group.test-d.ts
- tests/foundry/client/pixi/core/containers/unbound-container.test-d.ts
- tests/foundry/client/pixi/groups/effects.test-d.ts
- tests/foundry/client/pixi/groups/environment.test-d.ts
- tests/foundry/client/pixi/groups/hidden.test-d.ts
- tests/foundry/client/pixi/groups/interface.test-d.ts
- tests/foundry/client/pixi/groups/overlay.test-d.ts
- tests/foundry/client/pixi/groups/primary.test-d.ts
- tests/foundry/client/pixi/groups/renderered.test-d.ts
and associated side effects (including changes to previously done mixins as discussed on discord)
> Types and tests for `pixi/groups` and `CanvasGroupMixin`

- src/foundry/client-esm/canvas/edges/collision.d.mts
- src/foundry/client-esm/canvas/edges/edge.d.mts
- src/foundry/client-esm/canvas/edges/edges.d.mts
- src/foundry/client-esm/canvas/edges/vertex.d.mts
- tests/foundry/client-esm/canvas/edges/collision.test-d.ts
- tests/foundry/client-esm/canvas/edges/edge.test-d.ts
- tests/foundry/client-esm/canvas/edges/vertex.test-d.ts
> Types and tests for `client-esm/canvas/edges/**`

- src/foundry/client/hooks.d.mts
Adds ApplicationV2 hook typing for v12; will need revision in v13 when they add in the Context & RenderOptions
Closes #2936
> Improved typing of hooks

- src/foundry/client-esm/client.d.mts
- src/foundry/client-esm/data/_module.d.mts
- src/foundry/client-esm/data/_types.d.mts
- src/foundry/client-esm/data/combat-config.d.mts
- src/foundry/client-esm/data/terrain-data.d.mts
- src/foundry/client-esm/types.d.mts
- src/foundry/client-esm/utils/_module.d.mts
- src/foundry/client-esm/utils/helpers.d.mts
Remaining stubs for new files in v13
> More v13 stubs

- src/foundry/client-esm/applications/api/application.d.mts
- src/foundry/client-esm/applications/api/dialog.d.mts
- src/foundry/client-esm/applications/api/document-sheet.d.mts
- src/foundry/client-esm/applications/sheets/ambient-light-config.d.mts
- src/foundry/client-esm/applications/sheets/ambient-sound-config.d.mts
- src/foundry/client-esm/applications/sheets/region-config.d.mts
- src/foundry/client-esm/applications/sidebar/sidebar-tab.d.mts
- src/foundry/client-esm/applications/ui/region-legend.d.mts
- tests/foundry/client-esm/applications/api/application.test-d.ts
- tests/foundry/client-esm/applications/ui/notifications.test-d.ts
Updated ApplicationV2, Implemented AbstractSidebarTab
Closes #3145 
Closes #3158
> ApplicationV2 and AbstractSidebarTab in v13.336

- src/foundry/client-esm/applications/api/application.d.mts
- src/foundry/client-esm/applications/api/handlebars-application.d.mts
> Updated HandlebarsApplicationMixin to v13.336

- src/foundry/client-esm/data/_module.d.mts
- src/foundry/client-esm/data/calendar.d.mts
- tests/foundry/client-esm/data/calendar.mjs.test-d.ts
Also had to report some bugs when I validated the provided simplified gregorian against the schema
https://github.com/foundryvtt/foundryvtt/issues/12249
Closes #12249
> Added CalendarData for 13.337

- src/foundry/client-esm/applications/_types.d.mts
- src/foundry/client-esm/applications/api/application.d.mts
- src/foundry/client-esm/applications/apps/_module.d.mts
- src/foundry/client-esm/applications/apps/combat-tracker-config.d.mts
- src/foundry/client-esm/applications/apps/document-ownership.d.mts
- src/foundry/client-esm/applications/apps/document-sheet-config.d.mts
- src/foundry/client-esm/applications/apps/file-picker.d.mts
- src/foundry/client-esm/applications/apps/grid-config.d.mts
- src/foundry/client-esm/applications/apps/image-popout.d.mts
- src/foundry/client-esm/applications/quickstart.d.mts
- tests/foundry/client-esm/applications/apps/file-picker.test-d.ts
Not sure how much to boilerplate the overrides here
Closes #3219
> Migrate FilePicker to AppV2 & 13.337

- src/foundry/client-esm/applications/api/application.d.mts
- src/foundry/client-esm/applications/api/document-sheet.d.mts
- src/foundry/client-esm/applications/ux/context-menu.d.mts
- tests/foundry/client-esm/applications/api/application.test-d.ts
- tests/foundry/client-esm/applications/api/document-sheet.test-d.ts
- tests/foundry/client-esm/applications/ui/context-menu.test-d.ts
- Removed the aborted 13.337 context menu handling and added in the new stuff
- Added in a basic implementation of the new submit handling; needs much more precise typing still
> Updated ContextMenu, ApplicationV2, and DocumentSheetV2 to 13.340

- src/foundry/client-esm/applications/api/handlebars-application.d.mts
> Updated HandlebarsApplicationMixin to 13.341

- src/foundry/client/data/documents/table-result.d.mts
- src/foundry/common/documents/table-result.d.mts
- tsdoc.json
This one's real small, but I stole the entire `tsdoc.json` from main so I can use `linkcode`, so that's nice
> Types for `TableResult`/`BaseTableResult`

- src/foundry/client/data/documents/region.d.mts
- src/foundry/client/data/documents/setting.d.mts
- src/foundry/client/data/documents/table-result.d.mts
- src/foundry/client/data/documents/token.d.mts
- src/foundry/client/data/documents/user.d.mts
- src/foundry/common/documents/active-effect.d.mts
- src/foundry/common/documents/actor-delta.d.mts
- src/foundry/common/documents/ambient-light.d.mts
- src/foundry/common/documents/ambient-sound.d.mts
- src/foundry/common/documents/drawing.d.mts
- src/foundry/common/documents/measured-template.d.mts
- src/foundry/common/documents/note.d.mts
- src/foundry/common/documents/region-behavior.d.mts
- src/foundry/common/documents/region.d.mts
- src/foundry/common/documents/setting.d.mts
- src/foundry/common/documents/table-result.d.mts
- src/foundry/common/documents/tile.d.mts
- src/foundry/common/documents/token.d.mts
- src/foundry/common/documents/user.d.mts
- src/foundry/common/documents/wall.d.mts
- tsdoc.json
I think the canvas documents missing schema fields made me think more of these would be non-trivial
> Types for `Setting`/`BaseSetting`

- src/foundry/client/applications/api/application.d.mts
> Updated AppV2 to 13.346

- src/foundry/client/canvas/animation/canvas-animation.d.mts
- src/foundry/client/canvas/board.d.mts
- src/foundry/client/canvas/interaction/mouse-handler.d.mts
- src/foundry/client/canvas/interaction/ping/alert.d.mts
- src/foundry/client/canvas/interaction/ping/arrow.d.mts
- src/foundry/client/canvas/interaction/ping/chevron.d.mts
- src/foundry/client/canvas/interaction/ping/ping.d.mts
- src/foundry/client/canvas/interaction/ping/pulse.d.mts
- src/foundry/client/canvas/interaction/render-flags.d.mts
- src/foundry/client/canvas/interaction/ruler/base-ruler.d.mts
- src/foundry/client/canvas/interaction/ruler/ruler.d.mts
- src/foundry/client/canvas/layers/controls.d.mts
- src/foundry/client/canvas/placeables/tokens/ruler.d.mts
- src/foundry/client/config.d.mts
- src/foundry/client/documents/user.d.mts
- src/foundry/common/grid/base.d.mts
- tests/foundry/client/canvas/interaction/mouse-handler.test-d.ts
- tests/foundry/client/canvas/interaction/ping/alert.test-d.ts
- tests/foundry/client/canvas/interaction/ping/arrow.test-d.ts
- tests/foundry/client/canvas/interaction/ping/chevron.test-d.ts
- tests/foundry/client/canvas/interaction/ping/ping.test-d.ts
- tests/foundry/client/canvas/interaction/ping/pulse.test-d.ts
- tests/foundry/client/canvas/interaction/render-flags.test-d.ts
- tests/foundry/client/canvas/interaction/ruler/base-ruler.test-d.ts
- tests/foundry/client/canvas/interaction/ruler/ruler.test-d.ts
- tests/foundry/client/canvas/layers/controls.test-d.ts
- tests/foundry/client/canvas/placeables/tokens/ruler.test-d.ts
The TODOs are beyond my capabilities
> Types and tests for `client/canvas/interaction/**` for 13.346
